import apple from "../assets/fruits/apple.png";
import bitterGourd from "../assets/vegitables/bitter gourd.png";
import blackgrapes from "../assets/fruits/black grapes.png";
import brocoli from "../assets/vegitables/brocoli.png";
import banana from "../assets/fruits/banana.png";
import beans from "../assets/vegitables/beans.png";
import berry from "../assets/fruits/berry.png";
import bottleGourd from "../assets/vegitables/bottle gourd.png";
import custardApple from "../assets/fruits/custard apple.png";
import cabbage from "../assets/vegitables/cabbage.png";
import grapes from "../assets/fruits/grapes.png";
import guava from "../assets/fruits/guava.png";
import capsicum from "../assets/vegitables/capsicum.png";
import carrot from "../assets/vegitables/carrot.png";
import lichi from "../assets/fruits/lichi.png";
import mango from "../assets/fruits/mango.png";
import ladiesFinger from "../assets/vegitables/Ladies finger.png";
import onion from "../assets/vegitables/onion.png";
import pea from "../assets/vegitables/pea.png";
import plum from "../assets/fruits/plum.png";
import potato from "../assets/vegitables/potato.png";
import pumpkin from "../assets/vegitables/pumpkin.png";
import pomegranate from "../assets/fruits/pomegranate.png";
import radish from "../assets/vegitables/radish.png";
import watermelon from "../assets/fruits/watermelon.png";
import tomato from "../assets/vegitables/tomato.png";
import chiku from "../assets/fruits/chiku.png";
import gooseberry from "../assets/fruits/gooseberry.png";
import cauliflower from "../assets/vegitables/cauliflower.png";
import cucumber from "../assets/vegitables/cucumber.png";
import mosambi from "../assets/fruits/mosambi.png";
import papaya from "../assets/fruits/papaya.png";
import ginger from "../assets/vegitables/ginger.png";
import methi from "../assets/vegitables/methi.png";
import pineapple from "../assets/fruits/pineapple.png";
import beetroot from "../assets/fruits/beetroot.png";
import mushroom from "../assets/vegitables/mushroom.png";
import orange from "../assets/fruits/orange.png";
import spinach from "../assets/vegitables/spinach.png";
import kiwi from '../assets/fruits/kiwi.png'
import arbi from '../assets/vegitables/Arbi colocasia.png'
import bathuwa from '../assets/vegitables/Bathuwa.png'
 import beans_broad from '../assets/vegitables/Beans broad.png'
 import brinjal from '../assets/vegitables/Brinjal.png'
 import tinda from '../assets/vegitables/Chappan Tinda.png'
 import chilli from '../assets/vegitables/Chilli.png'
 import curry_leave from '../assets/vegitables/Curry leaves.png'
 import dhaniya from '../assets/vegitables/Dhaniya.png'
 import garlic from '../assets/vegitables/Garlic.png'
 import green_banana from '../assets/vegitables/Green Banana.png'
 import green_chilli from '../assets/vegitables/Green Chilli.png'
 import mint_leaves from '../assets/vegitables/Mint Leaves.png'
 import rai_saag from '../assets/vegitables/Rai Saag.png'
 import red_cabbage from '../assets/vegitables/Red Cabbage.png'
 import red_potato from '../assets/vegitables/Red Potato.png'
 import spring_onion from '../assets/vegitables/Spring Onion.png'
 import avacado from '../assets/fruits/Avacado.png'
 import dragon_fruit from '../assets/fruits/Dragon Fruit.png'
 import strawberry from '../assets/fruits/Strawberry.png'
 import sweet_potato from '../assets/fruits/Sweet Potato.png'
// Grains
import atta_ashirvaad from "../assets/grocery/Grains/Ashirvaad_atta.png";
import atta_fortune from "../assets/grocery/Grains/fortune_atta_5kg.png";
import rice_fortune from "../assets/grocery/Grains/Fortune_Basmati_Rice_5kg.png";
import indiaGate_Everyday from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Everyday.png";
import indiaGate_miniMogra from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Mini_Mogra.png";
import indiaGate_Mogra from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Mogra.png";
import indiaGate_Regular from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Regular.png";
import indiaGate_Super from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Super.png";
import Nature_fresh from "../assets/grocery/Grains/Nature_fresh_atta.png";
import poha_fortune from "../assets/grocery/Grains/Poha fortune.png";
import poha_rajdhani from "../assets/grocery/Grains/Poha rajdhani.png";
import maida_fortune from "../assets/grocery/Grains/Maida fortune.png";
import maida_rajdhani from "../assets/grocery/Grains/Maida rajdhani.png";
import besan_fortune from "../assets/grocery/Grains/Besan fortune.png";
import besan_rajdhani from "../assets/grocery/Grains/Besan rajdhani.png"
import daliya_rajdhani from '../assets/grocery/Grains/Daliya.png'
// Dry fruits
import almonds from "../assets/grocery/Dry-Fruits/Almonds.png";
import anjir from "../assets/grocery/Dry-Fruits/Anjir.png";
import cashew_flipcart from "../assets/grocery/Dry-Fruits/Cashew_flipcart.png";
import cashew_tata from "../assets/grocery/Dry-Fruits/Cashew_tata.png";
import chia_seeds from "../assets/grocery/Dry-Fruits/Chia Seeds.png";
import dates from "../assets/grocery/Dry-Fruits/Dates.png";
import makhana_flipcart from "../assets/grocery/Dry-Fruits/Makhana_flipcart.png";
import makhana_zoff from "../assets/grocery/Dry-Fruits/Makhana_Zoff.png";
import peanut from "../assets/grocery/Dry-Fruits/Peanut.png";
import pumpkin_seeds from "../assets/grocery/Dry-Fruits/Pumpkin Seeds.png";
import raisins_flipcart from "../assets/grocery/Dry-Fruits/Raisins_flipcart.png";
import raisins_tata from "../assets/grocery/Dry-Fruits/Raisins_tata.png";
import walnut from "../assets/grocery/Dry-Fruits/Walnut.png";
// Ghee & Oil
import ghee_ashirvaad from '../assets/grocery/Ghee & Oil/Aashirvaad_ghee.png'
import ghee_amul from '../assets/grocery/Ghee & Oil/Amul_Ghee.png'
import ghee_ananda from '../assets/grocery/Ghee & Oil/Ananda_Ghee.png'
import dalda_1kg from '../assets/grocery/Ghee & Oil/Dalda 1kg.png'
import dalda_5kg from '../assets/grocery/Ghee & Oil/Dalda 5kg.png'
import oil_dhara from '../assets/grocery/Ghee & Oil/Dhara_oil.png'
import oil_dhara_pouch from '../assets/grocery/Ghee & Oil/Dhara_oil_Pouch.png'
import oil_fortune from '../assets/grocery/Ghee & Oil/fortune_oil_1ltr.png'
import oil_fortune_2 from '../assets/grocery/Ghee & Oil/Fortune_oil_2.5lt.png'
import oil_fortune_pouch from '../assets/grocery/Ghee & Oil/Fortune_oil_Pouch.png'
import ghee_godrej from '../assets/grocery/Ghee & Oil/Ghee(godrej).png'
import ghee_govardhan from '../assets/grocery/Ghee & Oil/Ghee(govardhan).png'
import refine_fortune from '../assets/grocery/Ghee & Oil/Refine(fortune).png'
// masala 
import chat_masala from '../assets/grocery/Masala/Chat masala.png'
import Chhole_masala from '../assets/grocery/Masala/Chhole Masala.png'
import chicken_masala_catch from '../assets/grocery/Masala/Chicken Masala(Catch).png'
import chicken_masala_mdh from '../assets/grocery/Masala/Chicken Masala(MDH).png'
import chilli_powder_catch from '../assets/grocery/Masala/Chilli Powder(catch).png'
import coriander_powder_catch from '../assets/grocery/Masala/Coriander Powder(catch).png'
import coriander_powder_tata from '../assets/grocery/Masala/Coriander Powder(tata).png'
import deggi_mirch from '../assets/grocery/Masala/Deggi mirch(MDH).png'
import garam_masala_catch from '../assets/grocery/Masala/Garam Masala(catch).png'
import garam_masala_everest from '../assets/grocery/Masala/Garam masala(everest).png'
import garam_masala_mdh from '../assets/grocery/Masala/Garam masala(MDH).png'
import garam_masala_tata from '../assets/grocery/Masala/Garam masala(tata).png'
import ginger_garlic from '../assets/grocery/Masala/Ginger garlic.png'
import jeera_powder_catch from '../assets/grocery/Masala/Jeera powder(catch).png'
import kashmiri_mirch_mdh from '../assets/grocery/Masala/Kashmiri mirch(MDH).png'
import kashmiri_powder_everest from '../assets/grocery/Masala/Kashmiri mirch(everest).png'
import kitchen_king_everest from '../assets/grocery/Masala/Kitchen king(everest).png'
import kitchen_king_mdh from '../assets/grocery/Masala/Kitchen king(MDH).png'
import kitchen_king_tata from '../assets/grocery/Masala/Kitchen king(tata).png'
import meat_masala_catch from '../assets/grocery/Masala/Meat masala(catch).png'
import meat_masala_mdh from '../assets/grocery/Masala/Meat masala(MDH).png'
import meat_masala_tata from '../assets/grocery/Masala/Meat masala(tata).png'
import sabji_masala_everest from '../assets/grocery/Masala/Sabji masala(everest).png'
import sabji_masala_goldie from '../assets/grocery/Masala/Sabji masala(goldie).png'
import shahi_paneer_MDH from '../assets/grocery/Masala/Shahi paneer(MDH).png'
import turmeric_powder_catch from '../assets/grocery/Masala/Turmeric powder(catch).png'
import turmeric_powder_flipcart from '../assets/grocery/Masala/Turmeric powder(flipcart).png'
// Nuts & Seeds
import masoor_black_flipcart from '../assets/grocery/Nuts & Seeds/Black Masoor dal.png'
import chanaDal_fortune from '../assets/grocery/Nuts & Seeds/Chana Dal(fortune).png'
import chana_rajdhani from '../assets/grocery/Nuts & Seeds/Chana rajdhani.png'
import chana_flipcart from '../assets/grocery/Nuts & Seeds/Chana.png'
import chanaDal_flipcart from '../assets/grocery/Nuts & Seeds/Chana dal.png'
import kabuli_flipcart from '../assets/grocery/Nuts & Seeds/Kabuli Chana(flipcart).png'
import kabuli_fortune from '../assets/grocery/Nuts & Seeds/Kabuli Chana(fortune).png'
import masoor_flipcart from '../assets/grocery/Nuts & Seeds/Masoor dal.png'
import mixed_dal from '../assets/grocery/Nuts & Seeds/Mixed dal.png'
import moong_dal_Chhilka from '../assets/grocery/Nuts & Seeds/Moong dal(chhilka).png'
import moong_dal_tata from '../assets/grocery/Nuts & Seeds/Moong dal(tata).png'
import moong from '../assets/grocery/Nuts & Seeds/Moong.png'
import moong_dal_flipcart from '../assets/grocery/Nuts & Seeds/Moong dal.png'
import rajma_flipcart from '../assets/grocery/Nuts & Seeds/Rajma(flipcart).png'
import rajma_fortune from '../assets/grocery/Nuts & Seeds/Rajma.png'
import soyachunk_flipcart from '../assets/grocery/Nuts & Seeds/Soya Chunk(flipcart).png'
import soyachunk_fortune from '../assets/grocery/Nuts & Seeds/Soya Chunk(fortune).png'
import Toor_dal from '../assets/grocery/Nuts & Seeds/Toor dal.png'
import urad_dal from '../assets/grocery/Nuts & Seeds/Urad dal.png'
import pea_flipcart from '../assets/grocery/Nuts & Seeds/White Pea.png'
// Sugar & Salt
import salt_black from '../assets/grocery/Suger & Salt/Black Salt.png'
import salt_pink from '../assets/grocery/Suger & Salt/Pink Salt.png'
import rock_salt_nature from '../assets/grocery/Suger & Salt/Black Salt.png'
import rock_salt_organic from '../assets/grocery/Suger & Salt/Rock Salt(organic).png'
import rock_salt_tata from '../assets/grocery/Suger & Salt/Rock Salt(tata).png'
import salt_immuno from '../assets/grocery/Suger & Salt/Salt Immuno.png'
import salt_lite from '../assets/grocery/Suger & Salt/Salt lite.png'
import salt from '../assets/grocery/Suger & Salt/Salt.png'
import sugarfree from '../assets/grocery/Suger & Salt/Suger free.png'
import sugar_sulpharfree from '../assets/grocery/Suger & Salt/Suger Sulpharfree.png'
import suger from '../assets/grocery/Suger & Salt/Suger.png'
// Whole Masala
import ajwain_flipcart from '../assets/grocery/Whole masala/Ajwain flipcart.png'
import ajwain_zoff from '../assets/grocery/Whole masala/Ajwain Zoff.png'
import cardamom_black from '../assets/grocery/Whole masala/Black Cardamom.png'
import black_peppar from '../assets/grocery/Whole masala/Black Peppar.png'
import black_peppar_flipcart from '../assets/grocery/Whole masala/Black Peppar(flipcart).png'
import cinnamon from '../assets/grocery/Whole masala/Cinnamon.png'
import clove_zoff from '../assets/grocery/Whole masala/Clove(Zoff).png'
import clove_flipcart from '../assets/grocery/Whole masala/Clove(flipcart).png'
import coriander_flipcart from '../assets/grocery/Whole masala/Coriander(flipcart).png'
import fenugreek from '../assets/grocery/Whole masala/Fenugreek.png'
import funnel_flipcart from '../assets/grocery/Whole masala/Funnel Seeds(flipcart).png'
import funnel_zoff from '../assets/grocery/Whole masala/Funnel Seeds(Zoff).png'
import garam_masala from '../assets/grocery/Whole masala/Garam masala.png'
import javitri from '../assets/grocery/Whole masala/Javitri.png'
import jeera_catch from '../assets/grocery/Whole masala/Jeera(catch).png'
import jeera_zoff from '../assets/grocery/Whole masala/Jeera(Zoff).png'
import kasturi_methi from '../assets/grocery/Whole masala/Kasturi methi(Zoff).png'
import lal_mirch from '../assets/grocery/Whole masala/Lal mirch.png'
import mustard_rai from '../assets/grocery/Whole masala/Mustard rai.png'
import tejpatta from '../assets/grocery/Whole masala/Tejpatta.png'



let allData=[
  // Fruits
  {
    id: 1,
    name: "Apple",
    img: apple,
    price: 160,
    qnty:"1 kg",
    description:"Indulge in the natural sweetness and crisp texture of fresh apples, handpicked from the finest orchards. Our apples are rich in essential nutrients, making them a perfect snack for a healthy lifestyle.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "15% off",qty:0,
  },
  {
    id: 2,
    name: "Black Grapes",
    img: blackgrapes,
    price: 140,
    qnty:"1 kg",
    description:"Handpicked from the finest farms, our black grapes are sweet, juicy, and packed with nutrients. Known for their deep purple hue and rich flavor, these grapes are an excellent source of antioxidants, vitamins, and minerals, promoting heart health and boosting immunity.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 3,
    name: "Banana",
    img: banana,
     price: 60,
    qnty:"12 piece",
    description:"Enjoy the rich, creamy texture and natural sweetness of our handpicked bananas, sourced from the best farms. Packed with essential vitamins, fiber, and potassium, bananas are a perfect energy booster for your daily diet.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 4,
    name: "Berry",
    img: berry,
     price: 120,
    qnty:"1 kg",
    description:"Savor the burst of natural sweetness with our premium-quality berries, rich in antioxidants, vitamins, and fiber. These nutrient-packed delights support immunity, heart health, and glowing skin. Perfect for snacking, smoothies, desserts, and salads!",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 5,
    name: "Custard Apple",
    img: custardApple,
    price: 180,
    qnty:"1 kg",
    description:" Enjoy the Rich, Creamy Delight of Custard Apple! Our premium-quality custard apples are handpicked to ensure freshness, sweetness, and a luscious texture. Known for their rich fiber, vitamin C, and antioxidants, custard apples support digestion, immunity, and overall well-being.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,

  },
  {
    id: 6,
    name: "Grapes",
    img: grapes,
    price: 140,
    qnty:"1 kg",
    description:"Savor the Sweetness of Fresh Grapes! Our premium grapes are picked from the finest vineyards, offering a burst of juiciness with every bite. Whether you enjoy them as a snack, in salads, or as part of your favorite dishes, these grapes are a natural source of vitamins, antioxidants, and hydration.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  
  },
  {
    id: 7,
    name: "Guava",
    img: guava,
    price: 70,
    qnty:"1 kg",
    description:"Enjoy the Zesty Freshness of Guava! Our handpicked guavas are bursting with flavor and packed with vitamins and minerals. Whether you enjoy them fresh or blended into smoothies, they make a refreshing snack while providing a boost to your health.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 8,
    name: "Lichi",
    img: lichi,
    price: 150,
    qnty:"1 kg",
    description:" Indulge in the Tropical Taste of Litchi! Our litchis are handpicked at the peak of freshness, offering a delicate, sweet flavor that is loved by all. Enjoy this exotic fruit as a refreshing snack or use it to enhance your desserts and beverages.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 9,
    name: "Mango",
    img: mango,
      price: 80,
    qnty:"1 kg",
    description:"Taste the tropical bliss with our fresh mangoes! Handpicked from the best orchards, these mangoes are packed with sweetness, juiciness, and a rich, tropical flavor that will leave you craving more. Perfect for enjoying on their own or adding to your fruit salads, smoothies, and desserts.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 10,
    name: "Plum",
    img: plum,
      price: 150,
    qnty:"1 kg",
    description:"Delight in the tangy sweetness of fresh plums! These juicy, vibrant plums are perfect for snacking, making refreshing juices, or adding to your favorite fruit salads and desserts. With their naturally sweet and slightly tart flavor, plums are the ideal balance of deliciousness and health benefits.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 11,
    name: "Pomegranate",
    img: pomegranate,
    price: 140,
    qnty:"1 kg",
    description:"A fruit known for its vibrant color, refreshing taste, and numerous health benefits! Packed with juicy seeds, each bite of this superfruit provides a delightful crunch and a burst of flavor. Perfect for snacking or adding to your smoothies, salads, and desserts.",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 12,
    name: "Watermelon",
    img: watermelon,
      price: 80,
    qnty:"1 kg",
    description:"Watermelon! Known for its juicy, sweet, and hydrating qualities, this tropical treat is perfect for beating the heat. Whether you're enjoying it by the slice, blending it into smoothies, or adding it to fruit salads, watermelon is the ideal refreshing snack.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 13,
    name: "Chiku",
    img: chiku,
      price: 80,
    qnty:"1 kg",
    description:"Indulge in the natural sweetness of Chiku, also known as Sapodilla! This tropical fruit is not only delicious but also packed with essential nutrients. With its soft, brown exterior and sweet, grainy flesh, Chiku is a treat for your taste buds and a healthy snack for your body.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 14,
    name: "Gooseberry",
    img: gooseberry,
    price: 40,
    qnty:"1 kg",
    description:"Discover the tangy goodness of Gooseberry (Amla), a powerhouse of nutrients! Packed with Vitamin C, antioxidants, and dietary fiber, this small but mighty fruit is known for its health-boosting properties and refreshing taste.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 15,
    name: "Mosambi",
    img: mosambi,
     price: 60,
    qnty:"1 kg",
    description:"Enjoy the refreshing and tangy taste of Mosambi (Sweet Lime), a citrus fruit packed with essential vitamins and minerals! Known for its sweet and slightly tangy flavor, Mosambi is a great way to hydrate and boost your immunity.",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 16,
    name: "Papaya",
    img: papaya,
    price: 70,
    qnty:"1 kg",
    description:" Experience the tropical sweetness and vibrant orange color of fresh Papaya, a fruit packed with essential nutrients that your body will love! Papaya is known for its high vitamin content and digestive benefits.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 17,
    name: "Pineapple",
    img: pineapple,
      price: 100,
    qnty:"1 kg",
    description:"Discover the refreshing sweetness and tang of fresh Pineapple, a tropical fruit that combines a juicy burst of flavor with numerous health benefits. Known for its vibrant yellow color and high vitamin content, Pineapple is a perfect addition to any meal or snack.",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 18,
    name: "Beet root",
    img: beetroot,
    price: 40,
    qnty:"1 kg",
    description:"Embrace the earthy goodness of fresh Beetroot, a powerhouse of nutrients that will elevate your meals and your health! With its rich color and rich nutritional profile, beetroot is not only a treat for your taste buds but also a natural boost for your body.",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 19,
    name: "Orange",
    img: orange,
    price: 70,
    qnty:"1 kg",
    description:"Savor the refreshing taste of juicy, sweet, and tangy Oranges, packed with vibrant flavor and essential nutrients. This citrus fruit is a perfect addition to your daily diet for a burst of freshness and vitality!",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 20,
    name: "Avacado",
    img: avacado,
     price: 120,
    qnty:"500 gm",
    description:"Indulge in the creamy richness of fresh Avocados, a versatile superfood perfect for your healthy lifestyle. With its smooth texture and rich flavor, Avocados are packed with healthy fats, making them a must-have for any meal.",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 21,
    name: "Dragon Fruit",
    img: dragon_fruit,
      price: 100,
    qnty:"500 gm",
    description:"Savor the vibrant and refreshing taste of Dragon Fruit, the exotic fruit packed with antioxidants and vitamins. Its unique appearance and mildly sweet flavor make it a perfect addition to your fruit collection.",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 22,
    name: "Strawberry",
    img: strawberry,
      price: 100,
    qnty:"250 gm",
    description:"Indulge in the juicy, sweet flavor of freshly picked strawberries, perfect for satisfying your cravings. These vibrant red berries are not only delicious but also packed with essential nutrients.",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 23,
    name: "Sweet Potato",
    img: sweet_potato,
      price: 50,
    qnty:"1 kg",
    description:" Delight in the rich, sweet flavor of fresh sweet potatoes, a versatile root vegetable packed with nutrients. Whether baked, mashed, or roasted, sweet potatoes offer a delightful and healthy addition to any meal.",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 24,
    name: "Kiwi",
    img: kiwi,
      price: 100,
    qnty:"4 piece",
    description:"Experience the refreshing tang of kiwi, packed with natural sweetness and a burst of tropical flavor. With its unique blend of tartness and sweetness, kiwi is the perfect fruit to enhance your daily nutrition.",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  // vegi 
  {
    id: 25,
    name: "Bitter Gourd",
    img: bitterGourd,
      price: 80,
      description:" Bitter Gourd, also known as Karela, a unique vegetable celebrated for its distinctive flavor and impressive health properties. This green, warty-skinned vegetable is a powerhouse of essential vitamins, minerals, and antioxidants, making it a must-have addition to your diet.",
    category: "Vegetables",
    variety: "Marrow Vegi",
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 26,
    name: "Brocoli",
    img: brocoli,
      price: 80,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 28,
    name: "Beans",
    img: beans,
      price: 50,
    qnty:"500 gm",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 29,
    name: "Bottle Gourd",
    img: bottleGourd,
    price: 40,
    description:"",
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 30,
    name: "Cabbage",
    img: cabbage,
      price: 50,
      description:"",
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 31,
    name: "Capsicum",
    img: capsicum,
      price: 50,
    qnty:"1 kg",
    description:"",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 32,
    name: "Carrot",
    img: carrot,
    price: 40,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 33,
    name: "Ladies Finger",
    img: ladiesFinger,
    price: 70,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 34,
    name: "Onion",
    img: onion,
    price: 40,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 35,
    name: "Pea",
    img: pea,
      price: 50,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 36,
    name: "Potato",
    img: potato,
     price: 30,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 37,
    name: "Pumpkin",
    img: pumpkin,
      price: 50,
      description:"",
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 38,
    name: "Radish",
    img: radish,
     price: 30,
     description:"",
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 39,
    name: "CauliFlower",
    img: cauliflower,
     price: 60,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 40,
    name: "Cucumber",
    img: cucumber,
      price: 50,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 41,
    name: "Ginger",
    img: ginger,
      price: 80,
    qnty:"500 gm",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 42,
    name: "Methi",
    img: methi,
    price: 40,
    qnty:"250 gm",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 43,
    name: "Mushroom",
    img: mushroom,
     price: 60,
    qnty:"250 gm",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 44,
    name: "Spinach",
    img: spinach,
      price: 80,
    qnty:"500 gm",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 45,
    name: "Arbi Colocasia",
    img: arbi,
      price: 80,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Root vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 46,
    name: "Bathuwa",
    img: bathuwa,
      price: 80,
      description:"",
    qnty:"500 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 47,
    name: "Beans Broad",
    img: beans_broad,
      price: 80,
      description:"",
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 48,
    name: "Brinjal",
    img: brinjal,
      price: 80,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 49,
    name: "Chappan Tinda",
    img: tinda,
      price: 100,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 50,
    name: "Chilli",
    img: chilli,
     price: 30,
    qnty:"100 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 51,
    name: "Curry Leaves",
    img: curry_leave,
     price: 60,
    qnty:"100 gm",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 52,
    name: "Dhaniya",
    img: dhaniya,
    price: 40,
    qnty:"100 gm",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 53,
    name: "Garlic",
    img: garlic,
      price: 100,
    qnty:"250 gm",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 54,
    name: "Green Banana",
    img: green_banana,
      price: 80,
    qnty:"12 piece",
    description:"",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 55,
    name: "Green Chilli",
    img: green_chilli,
      price: 50,
    qnty:"250 gm",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 56,
    name: "Mint Leaves",
    img: mint_leaves,
      price: 50,
    qnty:"100 gm",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 57,
    name: "Raai Saag",
    img: rai_saag,
      price: 80,
    qnty:"250 gm",
    description:"",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 58,
    name: "Red Cabbage",
    img: red_cabbage,
      price: 100,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 59,
    name: "Red Potato",
    img: red_potato,
      price: 80,
    qnty:"1 kg",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 60,
    name: "Spring Onion",
    img: spring_onion,
      price: 100,
    qnty:"250 gm",
    description:"",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  // Grains
  {
    id: 61,
    name: "Aashirvaad Atta",
    img: atta_ashirvaad,
     price: 220,
    category: "Grocery",
    variety: "Grains",
    qnty:"5 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 62,
    name: "Fortune Atta",
    img: atta_fortune,
     price: 210,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 63,
    name: "Fortune Besan",
    img: besan_fortune,
     price: 99,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 64,
    name: "Rajdhani Besan",
    img: besan_rajdhani,
     price: 109,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 65,
    name: "Daliya Rajdhani",
    img: daliya_rajdhani,
    price: 76,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 66,
    name: "Fortune Basmati Rice",
    img: rice_fortune,
     price: 535,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 67,
    name: "India Gate Basmati Rice (Everyday)",
    img: indiaGate_Everyday,
     price: 355,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 68,
    name: "India Gate Basmati Rice (Mini Mogra)",
    img: indiaGate_miniMogra,
    price: 290,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 69,
    name: "India Gate Basmati Rice (Mogra)",
    img: indiaGate_Mogra,
    price: 345,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 70,
    name: "India Gate Basmati Rice (Regular)",
    img: indiaGate_Regular,
    price: 380,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 71,
    name: "India Gate Basmati Rice (Super)",
    img: indiaGate_Super,
     price: 780,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 72,
    name: "Nature Fresh Atta",
    img: Nature_fresh,
     price: 230,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 73,
    name: "Fortune Poha",
    img: poha_fortune,
     price: 51,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 74,
    name: "Fortune Maida",
    img: maida_fortune,
    price: 40,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 75,
    name: "Rajdhani Maida",
    img: maida_rajdhani,
    price: 40,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 76,
    name: "Rajdhani Poha",
    img: poha_rajdhani,
    price: 40,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  // Masala
  {
    id: 77,
    name: "Chat Masala",
    img:chat_masala ,
     price: 60,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 78,
    name: "Chhole Masala",
    img:Chhole_masala ,
      price: 50,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 79,
    name: "Chicken Masala",
    img:chicken_masala_catch,
      price: 80,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 80,
    name: "Chicken Masala",
    img:chicken_masala_mdh ,
    price: 79,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 81,
    name: "Chilli Powder",
    img:chilli_powder_catch ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 82,
    name: "Coriander Powder",
    img:coriander_powder_catch ,
     price: 35,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 83,
    name: "Coriander Powder",
    img:coriander_powder_tata ,
     price: 45,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 84,
    name: "Deggi Mirch",
    img:deggi_mirch ,
    price: 95,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 85,
    name: "Garam Masala",
    img:garam_masala_catch ,
     price: 90,
    qnty:"200 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 86,
    name: "Garam Masala",
    img:garam_masala_everest ,
      price: 80,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 87,
    name: "Garam Masala",
    img:garam_masala_mdh ,
    price: 95,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 88,
    name: "Garam Masala",
    img:garam_masala_tata ,
     price: 110,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 89,
    name: "Ginger & Garlic Paste",
    img:ginger_garlic ,
     price: 45,
    qnty:"150 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 90,
    name: "Jeera Powder",
    img:jeera_powder_catch ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 91,
    name: "Kashmiri Mirch",
    img:kashmiri_mirch_mdh ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 92,
    name: "Kashmiri Powder",
    img:kashmiri_powder_everest ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 93,
    name: "Kitchen King",
    img:kitchen_king_everest ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 94,
    name: "Kitchen King",
    img:kitchen_king_mdh ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  { 
    id: 95,
    name: "Kitchen King",
    img:kitchen_king_tata ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 96,
    name: "Meat Masala",
    img:meat_masala_catch ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 97,
    name: "Meat Masala",
    img:meat_masala_mdh ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 98,
    name: "Meat Masala",
    img:meat_masala_tata ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 99,
    name: "Sabji Masala",
    img:sabji_masala_everest ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 100,
    name: "Sabji Masala",
    img:sabji_masala_goldie ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 101,
    name: "Shahi Paneer Masala",
    img:shahi_paneer_MDH,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 102,
    name: "Turmeric Powder",
    img:turmeric_powder_catch ,
     price: 90,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 103,
    name: "Turmeric Powder",
    img:turmeric_powder_flipcart ,
     price: 90,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  // Dry Fruits
  {
    id: 104,
    name: "Almonds",
    img: almonds,
     price: 250,
    category: "Grocery",
    variety: "Dry Fruits",
    qnty:"250 gm",
    offer: "10% off",qty:0,
  },
  {
    id: 105,
    name: "Dates",
    img: dates,
     price: 191,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 106,
    name: "Peanut",
    img: peanut,
    price: 140,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 107,
    name: "Makhana Classic",
    img: makhana_flipcart,
    price: 180,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 108,
    name: "Makhana ZOFF",
    img: makhana_zoff,
   price: 190,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 109,
    name: "Chia Seeds",
    img: chia_seeds,
      price: 150,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 110,
    name: "Raisins(Kismis)",
    img: raisins_flipcart,
     price: 210,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 111,
    name: "Raisins(Kismis)",
    img: raisins_tata,
     price: 240,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 112,
    name: "Pumpkin Seeds",
    img: pumpkin_seeds,
    price: 140,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 113,
    name: "Anjir Classic",
    img: anjir,
     price: 280,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 114,
    name: "Cashew Classic Kaju",
    img: cashew_flipcart,
     price: 300,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 115,
    name: "Cashew ZOFF Kaju ",
    img: cashew_tata,
    price: 290,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 116,
    name: "Walnut ",
    img: walnut,
     price: 200,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  // Ghee & Oil
  {
    id: 117,
    name: "Aashirvaad Ghee ",
    img: ghee_ashirvaad,
     price: 500,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 118,
    name: "Amul Ghee ",
    img: ghee_amul,
     price: 550,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 119,
    name: "Ananda Ghee ",
    img: ghee_ananda,
     price: 501,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 120,
    name: "Dalda 1kg",
    img: dalda_1kg,
    price: 140,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 121,
    name: "Dalda 5kg ",
    img: dalda_5kg,
    price: 685,
    qnty:"5 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 122,
    name: "Dhara Oil ",
    img: oil_dhara,
     price: 155,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 123,
    name: "Dhara Oil Pouch ",
    img: oil_dhara_pouch,
     price: 145,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 124,
    name: "Fortune Oil ",
    img: oil_fortune,
     price: 165,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 125,
    name: "Fortune Oil 2.5 ltr ",
    img: oil_fortune_2,
     price: 350,
    qnty:"2.5 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 126,
    name: "Fortune Oil Pouch ",
    img:oil_fortune_pouch,
     price: 160,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 127,
    name: "Godrej Ghee ",
    img: ghee_godrej,
    price: 450,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 128,
    name: "Govardhan Ghee ",
    img: ghee_govardhan,
    price: 650,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 129,
    name: "Fortune Refine ",
    img: refine_fortune,
   price: 750,
    qnty:"5 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  // Whole Masala
  {
    id: 130,
    name: "Classic Ajwain",
    img: ajwain_flipcart,
     price: 51,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 131,
    name: "Zoff Ajwain",
    img: ajwain_zoff,
    price: 55,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 132,
    name: "Black Cardamom",
    img: cardamom_black,
    price: 65,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 133,
    name: "Black Peppar",
    img: black_peppar,
     price: 120,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 134,
    name: "Classic Black Peppar",
    img: black_peppar_flipcart,
    price: 105,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 135,
    name: "Cinnamon",
    img: cinnamon,
      price: 50,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 136,
    name: "Clove/Laung ZOff",
    img: clove_zoff,
    price: 65,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 137,
    name: "Classic Clove/Laung",
    img: clove_flipcart,
     price: 60,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 138,
    name: "Classic Coriander",
    img: coriander_flipcart,
     price: 45,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 139,
    name: "Fenugreek/Methi Zoff",
    img: fenugreek,
      price: 50,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 140,
    name: "Classic Funnel Seeds",
    img: funnel_flipcart,
    price: 55,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 141,
    name: "Funnel Seeds Zoff",
    img: funnel_zoff,
     price: 51,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 142,
    name: "Garam Masala",
    img: garam_masala,
  price: 75,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 143,
    name: "Javitri",
    img: javitri,
    price: 85,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 144,
    name: "Whole Jeera",
    img: jeera_catch,
    price: 55,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 145,
    name: "Whole Jeera",
    img: jeera_zoff,
     price: 51,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 146,
    name: "Kasturi Methi",
    img: kasturi_methi,
     price: 45,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 147,
    name: "Lal Mirch",
    img: lal_mirch,
     price: 51,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 148,
    name: "Classic Mustard Rai",
    img: mustard_rai,
     price: 45,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 149,
    name: "Classic Tejpatta",
    img: tejpatta,
     price: 45,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  // sugar & Salt
  {
    id: 150,
    name: "Pink Salt",
    img: salt_pink,
    price: 55,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 151,
    name: "Black Salt",
    img: salt_black,
    price: 40,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 152,
    name: "Tata Salt",
    img: salt,
     price: 45,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 153,
    name: "Rock Salt",
    img: rock_salt_nature,
    price: 55,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 154,
    name: "Rock Salt",
    img: rock_salt_tata,
     price: 60,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 155,
    name: "Rock Salt",
    img: rock_salt_organic,
    price: 65,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 156,
    name: "Salt Lite",
    img: salt_lite,
      price: 50,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 157,
    name: "Sugar Free",
    img: sugarfree,
     price: 300,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 158,
    name: "Sulpharfree Sugar",
    img: sugar_sulpharfree,
  price: 75,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 159,
    name: "Fortune Sugar",
    img: suger,
    price: 55,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 160,
    name: "Salt Immuno",
    img: salt_immuno,
    price: 65,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  // Nuts & Seed
  {
    id: 161,
    name: "Black Masoor Dal",
    img:masoor_black_flipcart ,
     price: 90,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 162,
    name: "Fortune Chana Dal",
    img:chanaDal_fortune ,
     price: 110,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 163,
    name: "Rajdhani Chana",
    img:chana_rajdhani ,
      price: 100,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 164,
    name: "Classic Chana",
    img:chana_flipcart ,
     price: 120,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 165,
    name: "Classic Chana Dal",
    img:chanaDal_flipcart ,
     price: 110,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 166,
    name: "Classic Kabuli Chana",
    img:kabuli_flipcart ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 167,
    name: "Fortune Kabuli Chana",
    img:kabuli_fortune ,
    price: 140,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 168,
    name: "Classic Masoor Dal",
    img:masoor_flipcart ,
     price: 130,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 169,
    name: "Mixed Dal",
    img:mixed_dal ,
     price: 130,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 170,
    name: "Moong Dal",
    img:moong_dal_Chhilka ,
     price: 160,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 171,
    name: "Moong Dal",
    img:moong_dal_tata ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 172,
    name: "Moong Saboot",
    img:moong ,
     price: 130,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 173,
    name: "Classic Moong Dal",
    img:moong_dal_flipcart ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 174,
    name: "Classic Rajma",
    img:rajma_flipcart ,
     price: 160,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 175,
    name: "Fortune Rajma",
    img:rajma_fortune ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 176,
    name: "Soya Chunk",
    img:soyachunk_flipcart ,
    price: 55,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 177,
    name: "Soya Chunk",
    img:soyachunk_fortune ,
     price: 60,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 178,
    name: "Classic Toor Dal",
    img:Toor_dal ,
     price: 170,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 179,
    name: "Urad Dal",
    img:urad_dal ,
     price: 130,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 180,
    name: "Classic White Pea",
    img:pea_flipcart ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },

]
export {allData}

let allFruit=[
  {
    id: 1,
    name: "Apple",
    img: apple,
    price: 160,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "15% off",qty:0,
  },
  {
    id: 2,
    name: "Black Grapes",
    img: blackgrapes,
    price: 140,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 3,
    name: "Banana",
    img: banana,
     price: 60,
    qnty:"12 piece",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 4,
    name: "Berry",
    img: berry,
     price: 120,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 5,
    name: "Custard Apple",
    img: custardApple,
    price: 180,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,

  },
  {
    id: 6,
    name: "Grapes",
    img: grapes,
    price: 140,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  
  },
  {
    id: 7,
    name: "Guava",
    img: guava,
    price: 70,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 8,
    name: "Lichi",
    img: lichi,
      price: 150,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 9,
    name: "Mango",
    img: mango,
      price: 80,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 10,
    name: "Plum",
    img: plum,
      price: 150,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 11,
    name: "Pomegranate",
    img: pomegranate,
    price: 140,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 12,
    name: "Watermelon",
    img: watermelon,
      price: 80,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 13,
    name: "Chiku",
    img: chiku,
      price: 80,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 14,
    name: "Gooseberry",
    img: gooseberry,
    price: 40,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 15,
    name: "Mosambi",
    img: mosambi,
     price: 60,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 16,
    name: "Papaya",
    img: papaya,
    price: 70,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 17,
    name: "Pineapple",
    img: pineapple,
      price: 100,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 18,
    name: "Beet root",
    img: beetroot,
    price: 40,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 19,
    name: "Orange",
    img: orange,
    price: 70,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 20,
    name: "Avacado",
    img: avacado,
     price: 120,
    qnty:"500 gm",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 21,
    name: "Dragon Fruit",
    img: dragon_fruit,
      price: 100,
    qnty:"500 gm",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 22,
    name: "Strawberry",
    img: strawberry,
      price: 100,
    qnty:"250 gm",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 23,
    name: "Sweet Potato",
    img: sweet_potato,
      price: 50,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 24,
    name: "Kiwi",
    img: kiwi,
      price: 100,
    qnty:"4 piece",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",qty:0,
  },
]
export {allFruit}

let fruit = [
  {
    id: 1,
    name: "Apple",
    img: apple,
    price: 140,
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 3,
    name: "Banana",
    img: banana,
     price: 60,
    qnty:"12 piece",
    offer: "10% off",qty:0,
  },
  {
    id: 24,
    name: "Kiwi",
    img: kiwi,
      price: 100,
    qnty:"4 piece",
    offer: "10% off",qty:0,
  },
  {
    id: 9,
    name: "Mango",
    img: mango,
     price: 120,
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 5,
    name: "Custard Apple",
    img: custardApple,
    price: 140,
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 7,
    name: "Guava",
    img: guava,
      price: 80,
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
];
export { fruit };

let allVegi=[
  {
    id: 25,
    name: "Bitter Gourd",
    img: bitterGourd,
      price: 80,
    category: "Vegetables",
    variety: "Marrow Vegi",
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 26,
    name: "Brocoli",
    img: brocoli,
      price: 80,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 28,
    name: "Beans",
    img: beans,
      price: 50,
    qnty:"500 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 29,
    name: "Bottle Gourd",
    img: bottleGourd,
    price: 40,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 30,
    name: "Cabbage",
    img: cabbage,
      price: 50,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 31,
    name: "Capsicum",
    img: capsicum,
      price: 50,
    qnty:"1 kg",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 32,
    name: "Carrot",
    img: carrot,
    price: 40,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 33,
    name: "Ladies Finger",
    img: ladiesFinger,
    price: 70,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 34,
    name: "Onion",
    img: onion,
    price: 40,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 35,
    name: "Pea",
    img: pea,
      price: 50,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 36,
    name: "Potato",
    img: potato,
     price: 30,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 37,
    name: "Pumpkin",
    img: pumpkin,
      price: 50,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 38,
    name: "Radish",
    img: radish,
     price: 30,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 39,
    name: "CauliFlower",
    img: cauliflower,
     price: 60,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 40,
    name: "Cucumber",
    img: cucumber,
      price: 50,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 41,
    name: "Ginger",
    img: ginger,
      price: 80,
    qnty:"500 gm",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 42,
    name: "Methi",
    img: methi,
    price: 40,
    qnty:"250 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 43,
    name: "Mushroom",
    img: mushroom,
     price: 60,
    qnty:"250 gm",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 44,
    name: "Spinach",
    img: spinach,
      price: 80,
    qnty:"500 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 45,
    name: "Arbi Colocasia",
    img: arbi,
      price: 80,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 46,
    name: "Bathuwa",
    img: bathuwa,
      price: 80,
    qnty:"500 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 47,
    name: "Beans Broad",
    img: beans_broad,
      price: 80,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 48,
    name: "Brinjal",
    img: brinjal,
      price: 80,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 49,
    name: "Chappan Tinda",
    img: tinda,
      price: 100,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 50,
    name: "Chilli",
    img: chilli,
     price: 30,
    qnty:"100 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 51,
    name: "Curry Leaves",
    img: curry_leave,
     price: 60,
    qnty:"100 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 52,
    name: "Dhaniya",
    img: dhaniya,
    price: 40,
    qnty:"100 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 53,
    name: "Garlic",
    img: garlic,
      price: 100,
    qnty:"250 gm",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 54,
    name: "Green Banana",
    img: green_banana,
      price: 80,
    qnty:"12 piece",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 55,
    name: "Green Chilli",
    img: green_chilli,
      price: 50,
    qnty:"250 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 56,
    name: "Mint Leaves",
    img: mint_leaves,
      price: 50,
    qnty:"100 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 57,
    name: "Raai Saag",
    img: rai_saag,
      price: 80,
    qnty:"250 gm",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",qty:0,
  },
  {
    id: 58,
    name: "Red Cabbage",
    img: red_cabbage,
      price: 100,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 59,
    name: "Red Potato",
    img: red_potato,
      price: 80,
    qnty:"1 kg",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
  {
    id: 60,
    name: "Spring Onion",
    img: spring_onion,
      price: 100,
    qnty:"250 gm",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",qty:0,
  },
]
export {allVegi}

let vegi = [
  {
    id: 26,
    name: "Brocoli",
    img: brocoli,
      price: 80,
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 34,
    name: "Onion",
    img: onion,
      price: 50,
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 37,
    name: "Pumpkin",
    img: pumpkin,
     price: 60,
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 44,
    name: "Spinach",
    img: spinach,
    price: 40,
    qnty:"250 gm",
    offer: "10% off",qty:0,
  },
  {
    id: 31,
    name: "Capsicum",
    img: capsicum,
     price: 60,
    qnty:"500 gm",
    offer: "10% off",qty:0,
  },
  {
    id: 40,
    name: "Cucumber",
    img: cucumber,
     price: 60,
    qnty:"1 kg",
    offer: "10% off",qty:0,
  },
];
export { vegi };

let allGrains=[
  {
    id: 61,
    name: "Aashirvaad Atta",
    img: atta_ashirvaad,
     price: 220,
    category: "Grocery",
    variety: "Grains",
    qnty:"5 kg",
    offer: "10% off",qty:0,
  },
  {
    id: 62,
    name: "Fortune Atta",
    img: atta_fortune,
     price: 210,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 63,
    name: "Fortune Besan",
    img: besan_fortune,
     price: 99,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 64,
    name: "Rajdhani Besan",
    img: besan_rajdhani,
     price: 109,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 65,
    name: "Daliya Rajdhani",
    img: daliya_rajdhani,
    price: 76,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 66,
    name: "Fortune Basmati Rice",
    img: rice_fortune,
     price: 535,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 67,
    name: "India Gate Basmati Rice (Everyday)",
    img: indiaGate_Everyday,
     price: 355,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 68,
    name: "India Gate Basmati Rice (Mini Mogra)",
    img: indiaGate_miniMogra,
    price: 290,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 69,
    name: "India Gate Basmati Rice (Mogra)",
    img: indiaGate_Mogra,
    price: 345,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 70,
    name: "India Gate Basmati Rice (Regular)",
    img: indiaGate_Regular,
    price: 380,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 71,
    name: "India Gate Basmati Rice (Super)",
    img: indiaGate_Super,
     price: 780,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 72,
    name: "Nature Fresh Atta",
    img: Nature_fresh,
     price: 230,
    qnty:"5 kg",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 73,
    name: "Fortune Poha",
    img: poha_fortune,
     price: 51,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 74,
    name: "Fortune Maida",
    img: maida_fortune,
    price: 40,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 75,
    name: "Rajdhani Maida",
    img: maida_rajdhani,
    price: 40,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
  {
    id: 76,
    name: "Rajdhani Poha",
    img: poha_rajdhani,
    price: 40,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",qty:0,
  },
]
export {allGrains}

let grains=[
    {
        id: 62,
        name: "Atta",
        img: atta_fortune,
         price: 210,
        qnty:"5 kg",
        offer: "10% off",qty:0,
      },
      {
        id: 66,
        name: "Basmati Rice",
        img: rice_fortune,
         price: 535,
        qnty:"5 kg",
        offer: "10% off",qty:0,
      },
      {
        id: 73,
        name: "Poha",
        img: poha_fortune,
         price: 60,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 63,
        name: "Besan",
        img: besan_fortune,
          price: 80,
        qnty:"100 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 65,
        name: "Daliya",
        img: daliya_rajdhani,
          price: 50,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 74,
        name: "Maida",
        img: maida_fortune,
        price: 55,
        qnty:"1 kg",
        offer: "10% off",qty:0,
      },

]
export {grains}

let allMasala=[
  {
    id: 77,
    name: "Chat Masala",
    img:chat_masala ,
     price: 60,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 78,
    name: "Chhole Masala",
    img:Chhole_masala ,
      price: 50,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 79,
    name: "Chicken Masala",
    img:chicken_masala_catch,
      price: 80,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 80,
    name: "Chicken Masala",
    img:chicken_masala_mdh ,
    price: 79,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 81,
    name: "Chilli Powder",
    img:chilli_powder_catch ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",qty:0,
  },
  {
    id: 82,
    name: "Coriander Powder",
    img:coriander_powder_catch ,
     price: 35,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 83,
    name: "Coriander Powder",
    img:coriander_powder_tata ,
     price: 45,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 84,
    name: "Deggi Mirch",
    img:deggi_mirch ,
    price: 95,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 85,
    name: "Garam Masala",
    img:garam_masala_catch ,
     price: 90,
    qnty:"200 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 86,
    name: "Garam Masala",
    img:garam_masala_everest ,
      price: 80,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 87,
    name: "Garam Masala",
    img:garam_masala_mdh ,
    price: 95,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 88,
    name: "Garam Masala",
    img:garam_masala_tata ,
     price: 110,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 89,
    name: "Ginger & Garlic Paste",
    img:ginger_garlic ,
     price: 45,
    qnty:"150 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 90,
    name: "Jeera Powder",
    img:jeera_powder_catch ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 91,
    name: "Kashmiri Mirch",
    img:kashmiri_mirch_mdh ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 92,
    name: "Kashmiri Powder",
    img:kashmiri_powder_everest ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 93,
    name: "Kitchen King",
    img:kitchen_king_everest ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 94,
    name: "Kitchen King",
    img:kitchen_king_mdh ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  { 
    id: 95,
    name: "Kitchen King",
    img:kitchen_king_tata ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 96,
    name: "Meat Masala",
    img:meat_masala_catch ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 97,
    name: "Meat Masala",
    img:meat_masala_mdh ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 98,
    name: "Meat Masala",
    img:meat_masala_tata ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 99,
    name: "Sabji Masala",
    img:sabji_masala_everest ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 100,
    name: "Sabji Masala",
    img:sabji_masala_goldie ,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 101,
    name: "Shahi Paneer Masala",
    img:shahi_paneer_MDH,
     price: 90,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 102,
    name: "Turmeric Powder",
    img:turmeric_powder_catch ,
     price: 90,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
  {
    id: 103,
    name: "Turmeric Powder",
    img:turmeric_powder_flipcart ,
     price: 90,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",qty:0,
  },
]
export {allMasala}

let masala = [
  {
    id: 79,
    name: "Chicken Masala",
    img: chicken_masala_catch,
      price: 80,
    qnty:"100 gm",
    offer: "10% off",qty:0,
  },
  {
    id: 81,
    name: "Chilli Powder",
    img: chilli_powder_catch,
     price: 90,
    qnty:"100 gm",
    offer: "10% off",qty:0,
  },
  {
    id: 82,
    name: "Coriander Powder",
    img: coriander_powder_catch,
     price: 35,
    qnty:"100 gm",
    offer: "15% off",qty:0,
  },
  {
    id: 85,
    name: "Garam Masala",
    img: garam_masala_catch,
      price: 100,
    qnty:"200 gm",
    offer: "15% off",qty:0,
  },
  {
    id: 94,
    name: "Kitchen King",
    img: kitchen_king_mdh,
     price: 90,
    qnty:"100 gm",
    offer: "15% off",qty:0,
  },
  {
    id: 96,
    name: "Meat Masala",
    img: meat_masala_catch,
     price: 90,
    qnty:"100 gm",
    offer: "15% off",qty:0,
  },
];
export {masala}

let allDry_Fruits=[
  {
    id: 104,
    name: "Almonds",
    img: almonds,
     price: 250,
    category: "Grocery",
    variety: "Dry Fruits",
    qnty:"250 gm",
    offer: "10% off",qty:0,
  },
  {
    id: 105,
    name: "Dates",
    img: dates,
     price: 191,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 106,
    name: "Peanut",
    img: peanut,
    price: 140,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 107,
    name: "Makhana Classic",
    img: makhana_flipcart,
    price: 180,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 108,
    name: "Makhana ZOFF",
    img: makhana_zoff,
   price: 190,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 109,
    name: "Chia Seeds",
    img: chia_seeds,
      price: 150,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 110,
    name: "Raisins(Kismis)",
    img: raisins_flipcart,
     price: 210,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 111,
    name: "Raisins(Kismis)",
    img: raisins_tata,
     price: 240,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 112,
    name: "Pumpkin Seeds",
    img: pumpkin_seeds,
    price: 140,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 113,
    name: "Anjir Classic",
    img: anjir,
     price: 280,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 114,
    name: "Cashew Classic Kaju",
    img: cashew_flipcart,
     price: 300,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 115,
    name: "Cashew ZOFF Kaju ",
    img: cashew_tata,
    price: 290,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
  {
    id: 116,
    name: "Walnut ",
    img: walnut,
     price: 200,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",qty:0,
  },
]
export {allDry_Fruits}

let dry_fruits=[
    {
        id: 104,
        name: "Almonds",
        img: almonds,
         price: 280,
        qnty:"250 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 105,
        name: "Dates",
        img: dates,
         price: 200,
        qnty:"250 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 106,
        name: "Peanut",
        img: peanut,
         price: 160,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 108,
        name: "Makhana",
        img: makhana_zoff,
         price: 200,
        qnty:"100 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 109,
        name: "Chia Seeds",
        img: chia_seeds,
          price: 150,
        qnty:"250 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 111,
        name: "Raisins(Kismis)",
        img: raisins_tata,
         price: 200,
        qnty:"250 gm",
        offer: "10% off",qty:0,
      },
]
export {dry_fruits}

let allGhee_oil=[
  {
    id: 117,
    name: "Aashirvaad Ghee ",
    img: ghee_ashirvaad,
     price: 500,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 118,
    name: "Amul Ghee ",
    img: ghee_amul,
     price: 550,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 119,
    name: "Ananda Ghee ",
    img: ghee_ananda,
     price: 501,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 120,
    name: "Dalda 1kg",
    img: dalda_1kg,
    price: 140,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 121,
    name: "Dalda 5kg ",
    img: dalda_5kg,
    price: 685,
    qnty:"5 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 122,
    name: "Dhara Oil ",
    img: oil_dhara,
     price: 155,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 123,
    name: "Dhara Oil Pouch ",
    img: oil_dhara_pouch,
     price: 145,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 124,
    name: "Fortune Oil ",
    img: oil_fortune,
     price: 165,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 125,
    name: "Fortune Oil 2.5 ltr ",
    img: oil_fortune_2,
     price: 350,
    qnty:"2.5 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 126,
    name: "Fortune Oil Pouch ",
    img:oil_fortune_pouch,
     price: 160,
    qnty:"1 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 127,
    name: "Godrej Ghee ",
    img: ghee_godrej,
    price: 450,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 128,
    name: "Govardhan Ghee ",
    img: ghee_govardhan,
    price: 650,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
  {
    id: 129,
    name: "Fortune Refine ",
    img: refine_fortune,
   price: 750,
    qnty:"5 litre",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",qty:0,
  },
]
export {allGhee_oil}

let ghee_oil=[
    {
        id: 117,
        name: "Aashirvaad Ghee",
        img: ghee_ashirvaad,
         price: 500,
        qnty:"1 kg",
        offer: "10% off",qty:0,
      },
      {
        id: 122,
        name: "Dhara Oil",
        img: oil_dhara,
         price: 170,
        qnty:"1 litre",
        offer: "10% off",qty:0,
      },
      {
        id: 120,
        name: "Dalda",
        img: dalda_1kg,
         price: 200,
        qnty:"1 kg",
        offer: "10% off",qty:0,
      },
      {
        id: 129,
        name: "Refine",
        img: refine_fortune,
        price: 850,
        qnty:"5 litre",
        offer: "10% off",qty:0,
      },
      {
        id: 128,
        name: "Govardhan Ghee",
        img: ghee_govardhan,
         price: 600,
        qnty:"1 kg",
        offer: "10% off",qty:0,
      },
      {
        id: 124,
        name: "Fortune Oil",
        img: oil_fortune,
        price: 175,
        qnty:"1 litre",
        offer: "10% off",qty:0,
      },
]
export {ghee_oil}

let allWhole_masala=[
  {
    id: 130,
    name: "Classic Ajwain",
    img: ajwain_flipcart,
     price: 51,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 131,
    name: "Zoff Ajwain",
    img: ajwain_zoff,
    price: 55,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 132,
    name: "Black Cardamom",
    img: cardamom_black,
    price: 65,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 133,
    name: "Black Peppar",
    img: black_peppar,
     price: 120,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 134,
    name: "Classic Black Peppar",
    img: black_peppar_flipcart,
    price: 105,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 135,
    name: "Cinnamon",
    img: cinnamon,
      price: 50,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 136,
    name: "Clove/Laung ZOff",
    img: clove_zoff,
    price: 65,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 137,
    name: "Classic Clove/Laung",
    img: clove_flipcart,
     price: 60,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 138,
    name: "Classic Coriander",
    img: coriander_flipcart,
     price: 45,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 139,
    name: "Fenugreek/Methi Zoff",
    img: fenugreek,
      price: 50,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 140,
    name: "Classic Funnel Seeds",
    img: funnel_flipcart,
    price: 55,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 141,
    name: "Funnel Seeds Zoff",
    img: funnel_zoff,
     price: 51,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 142,
    name: "Garam Masala",
    img: garam_masala,
  price: 75,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 143,
    name: "Javitri",
    img: javitri,
    price: 85,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 144,
    name: "Whole Jeera",
    img: jeera_catch,
    price: 55,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 145,
    name: "Whole Jeera",
    img: jeera_zoff,
     price: 51,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 146,
    name: "Kasturi Methi",
    img: kasturi_methi,
     price: 45,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 147,
    name: "Lal Mirch",
    img: lal_mirch,
     price: 51,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 148,
    name: "Classic Mustard Rai",
    img: mustard_rai,
     price: 45,
    qnty:"100 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
  {
    id: 149,
    name: "Classic Tejpatta",
    img: tejpatta,
     price: 45,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",qty:0,
  },
]
export {allWhole_masala}

let whole_masala=[
    {
        id: 131,
        name: "Ajwain",
        img: ajwain_zoff,
        price: 40,
        qnty:"100 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 135,
        name: "Cinnamon",
        img: cinnamon,
         price: 45,
        qnty:"50 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 142,
        name: "Garam Masala",
        img: garam_masala,
      price: 75,
        qnty:"100 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 141,
        name: "Funnel Seeds",
        img: funnel_zoff,
         price: 60,
        qnty:"100 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 144,
        name: "Jeera",
        img: jeera_catch,
         price: 45,
        qnty:"100 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 149,
        name: "Tejpatta",
        img: tejpatta,
         price: 30,
        qnty:"50 gm",
        offer: "10% off",qty:0,
      },
]
export {whole_masala}

let allSugar_salt=[
  {
    id: 150,
    name: "Pink Salt",
    img: salt_pink,
    price: 55,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 151,
    name: "Black Salt",
    img: salt_black,
    price: 40,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 152,
    name: "Tata Salt",
    img: salt,
     price: 45,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 153,
    name: "Rock Salt",
    img: rock_salt_nature,
    price: 55,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 154,
    name: "Rock Salt",
    img: rock_salt_tata,
     price: 60,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 155,
    name: "Rock Salt",
    img: rock_salt_organic,
    price: 65,
    qnty:"500 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 156,
    name: "Salt Lite",
    img: salt_lite,
      price: 50,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 157,
    name: "Sugar Free",
    img: sugarfree,
     price: 300,
    qnty:"50 gm",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 158,
    name: "Sulpharfree Sugar",
    img: sugar_sulpharfree,
  price: 75,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 159,
    name: "Fortune Sugar",
    img: suger,
    price: 55,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
  {
    id: 160,
    name: "Salt Immuno",
    img: salt_immuno,
    price: 65,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",qty:0,
  },
]
export {allSugar_salt}

let suger_salt=[
    {
        id: 150,
        name: "Pink Salt",
        img: salt_pink,
      price: 75,
        qnty:"1 kg",
        offer: "10% off",qty:0,
      },
      {
        id: 151,
        name: "Balck Salt",
        img: salt_black,
         price: 45,
        qnty:"200 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 152,
        name: "Tata Salt",
        img: salt,
         price: 35,
        qnty:"1 kg",
        offer: "10% off",qty:0,
      },
      {
        id: 155,
        name: "Rock Salt",
        img: rock_salt_organic,
          price: 50,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 156,
        name: "Salt Lite",
        img: salt_lite,
        price: 40,
        qnty:"1 kg",
        offer: "10% off",qty:0,
      },
      {
        id: 158,
        name: "Sulpharfree Sugar",
        img: sugar_sulpharfree,
         price: 60,
        qnty:"1 kg",
        offer: "10% off",qty:0,
      },
]
export {suger_salt}

let allNuts_seed=[
  {
    id: 161,
    name: "Black Masoor Dal",
    img:masoor_black_flipcart ,
     price: 90,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 162,
    name: "Fortune Chana Dal",
    img:chanaDal_fortune ,
     price: 110,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 163,
    name: "Rajdhani Chana",
    img:chana_rajdhani ,
      price: 100,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 164,
    name: "Classic Chana",
    img:chana_flipcart ,
     price: 120,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 165,
    name: "Classic Chana Dal",
    img:chanaDal_flipcart ,
     price: 110,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 166,
    name: "Classic Kabuli Chana",
    img:kabuli_flipcart ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 167,
    name: "Fortune Kabuli Chana",
    img:kabuli_fortune ,
    price: 140,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 168,
    name: "Classic Masoor Dal",
    img:masoor_flipcart ,
     price: 130,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 169,
    name: "Mixed Dal",
    img:mixed_dal ,
     price: 130,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 170,
    name: "Moong Dal",
    img:moong_dal_Chhilka ,
     price: 160,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 171,
    name: "Moong Dal",
    img:moong_dal_tata ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 172,
    name: "Moong Saboot",
    img:moong ,
     price: 130,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 173,
    name: "Classic Moong Dal",
    img:moong_dal_flipcart ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 174,
    name: "Classic Rajma",
    img:rajma_flipcart ,
     price: 160,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 175,
    name: "Fortune Rajma",
    img:rajma_fortune ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 176,
    name: "Soya Chunk",
    img:soyachunk_flipcart ,
    price: 55,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 177,
    name: "Soya Chunk",
    img:soyachunk_fortune ,
     price: 60,
    qnty:"250 gm",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 178,
    name: "Classic Toor Dal",
    img:Toor_dal ,
     price: 170,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 179,
    name: "Urad Dal",
    img:urad_dal ,
     price: 130,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
  {
    id: 180,
    name: "Classic White Pea",
    img:pea_flipcart ,
      price: 150,
    qnty:"1 kg",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",qty:0,
  },
]
export {allNuts_seed}

let nuts_Seeds=[
    {
        id: 163,
        name: "Rajdhani Chana",
        img: chana_rajdhani,
         price: 60,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 176,
        name: "Soya Chunks",
        img: soyachunk_fortune,
        price: 55,
        qnty:"250 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 175,
        name: "Rajma",
        img: rajma_fortune,
          price: 100,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 169,
        name: "Mixed Dal",
        img: mixed_dal,
        price: 140,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 167,
        name: "Kabuli Chana",
        img: kabuli_fortune,
         price: 90,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
      {
        id: 162,
        name: "Chana Dal",
        img: chanaDal_fortune,
         price: 110,
        qnty:"500 gm",
        offer: "10% off",qty:0,
      },
]
export {nuts_Seeds}

