import apple from "../assets/fruits/apple.png";
import bitterGourd from "../assets/vegitables/bitter gourd.png";
import blackgrapes from "../assets/fruits/black grapes.png";
import brocoli from "../assets/vegitables/brocoli.png";
import banana from "../assets/fruits/banana.png";
import beans from "../assets/vegitables/beans.png";
import berry from "../assets/fruits/berry.png";
import bottleGourd from "../assets/vegitables/bottle gourd.png";
import custardApple from "../assets/fruits/custard apple.png";
import cabbage from "../assets/vegitables/cabbage.png";
import grapes from "../assets/fruits/grapes.png";
import guava from "../assets/fruits/guava.png";
import capsicum from "../assets/vegitables/capsicum.png";
import carrot from "../assets/vegitables/carrot.png";
import lichi from "../assets/fruits/lichi.png";
import mango from "../assets/fruits/mango.png";
import ladiesFinger from "../assets/vegitables/ladiesfinger.png";
import onion from "../assets/vegitables/onion.png";
import pea from "../assets/vegitables/pea.png";
import plum from "../assets/fruits/plum.png";
import potato from "../assets/vegitables/potato.png";
import pumpkin from "../assets/vegitables/pumpkin.png";
import pomegranate from "../assets/fruits/pomegranate.png";
import radish from "../assets/vegitables/radish.png";
import watermelon from "../assets/fruits/watermelon.png";
import tomato from "../assets/vegitables/tomato.png";
import chiku from "../assets/fruits/chiku.png";
import gooseberry from "../assets/fruits/gooseberry.png";
import cauliflower from "../assets/vegitables/cauliflower.png";
import cucumber from "../assets/vegitables/cucumber.png";
import mosambi from "../assets/fruits/mosambi.png";
import papaya from "../assets/fruits/papaya.png";
import ginger from "../assets/vegitables/ginger.png";
import methi from "../assets/vegitables/methi.png";
import pineapple from "../assets/fruits/pineapple.png";
import beetroot from "../assets/fruits/beetroot.png";
import mushroom from "../assets/vegitables/mushroom.png";
import orange from "../assets/fruits/orange.png";
import spinach from "../assets/vegitables/spinach.png";
import kiwi from '../assets/fruits/kiwi.png'
// Grains
import atta_ashirvaad from "../assets/grocery/Grains/Ashirvaad_atta.png";
import atta_fortune from "../assets/grocery/Grains/fortune_atta_5kg.png";
import rice_fortune from "../assets/grocery/Grains/Fortune_Basmati_Rice_5kg.png";
import indiaGate_Everyday from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Everyday.png";
import indiaGate_miniMogra from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Mini_Mogra.png";
import indiaGate_Mogra from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Mogra.png";
import indiaGate_Regular from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Regular.png";
import indiaGate_Super from "../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Super.png";
import Nature_fresh from "../assets/grocery/Grains/Nature_fresh_atta.png";
import poha_fortune from "../assets/grocery/Grains/Poha fortune.png";
import poha_rajdhani from "../assets/grocery/Grains/Poha rajdhani.png";
import maida_fortune from "../assets/grocery/Grains/Maida fortune.png";
import maida_rajdhani from "../assets/grocery/Grains/Maida rajdhani.png";
import besan_fortune from "../assets/grocery/Grains/Besan fortune.png";
import besan_rajdhani from "../assets/grocery/Grains/Besan rajdhani.png"
import daliya_rajdhani from '../assets/grocery/Grains/Daliya.png'
// Dry fruits
import almonds from "../assets/grocery/Dry-Fruits/Almonds.png";
import anjir from "../assets/grocery/Dry-Fruits/Anjir.png";
import cashew_flipcart from "../assets/grocery/Dry-Fruits/Cashew_flipcart.png";
import cashew_tata from "../assets/grocery/Dry-Fruits/Cashew_tata.png";
import chia_seeds from "../assets/grocery/Dry-Fruits/Chia Seeds.png";
import dates from "../assets/grocery/Dry-Fruits/Dates.png";
import makhana_flipcart from "../assets/grocery/Dry-Fruits/Makhana_flipcart.png";
import makhana_zoff from "../assets/grocery/Dry-Fruits/Makhana_Zoff.png";
import peanut from "../assets/grocery/Dry-Fruits/Peanut.png";
import pumpkin_seeds from "../assets/grocery/Dry-Fruits/Pumpkin Seeds.png";
import raisins_flipcart from "../assets/grocery/Dry-Fruits/Raisins_flipcart.png";
import raisins_tata from "../assets/grocery/Dry-Fruits/Raisins_tata.png";
import walnut from "../assets/grocery/Dry-Fruits/Walnut.png";
// Ghee & Oil
import ghee_ashirvaad from '../assets/grocery/Ghee & Oil/Aashirvaad_ghee.png'
import ghee_amul from '../assets/grocery/Ghee & Oil/Amul_Ghee.png'
import ghee_ananda from '../assets/grocery/Ghee & Oil/Ananda_Ghee.png'
import dalda_1kg from '../assets/grocery/Ghee & Oil/Dalda 1kg.png'
import dalda_5kg from '../assets/grocery/Ghee & Oil/Dalda 5kg.png'
import oil_dhara from '../assets/grocery/Ghee & Oil/Dhara_oil.png'
import oil_dhara_pouch from '../assets/grocery/Ghee & Oil/Dhara_oil_Pouch.png'
import oil_fortune from '../assets/grocery/Ghee & Oil/fortune_oil_1ltr.png'
import oil_fortune_2 from '../assets/grocery/Ghee & Oil/Fortune_oil_2.5lt.png'
import oil_fortune_pouch from '../assets/grocery/Ghee & Oil/Fortune_oil_Pouch.png'
import ghee_godrej from '../assets/grocery/Ghee & Oil/Ghee(godrej).png'
import ghee_govardhan from '../assets/grocery/Ghee & Oil/Ghee(govardhan).png'
import refine_fortune from '../assets/grocery/Ghee & Oil/Refine(fortune).png'
// masala 
import chat_masala from '../assets/grocery/Masala/Chat masala.png'
import Chhole_masala from '../assets/grocery/Masala/Chhole Masala.png'
import chicken_masala_catch from '../assets/grocery/Masala/Chicken Masala(Catch).png'
import chicken_masala_mdh from '../assets/grocery/Masala/Chicken Masala(MDH).png'
import chilli_powder_catch from '../assets/grocery/Masala/Chilli Powder(catch).png'
import coriander_powder_catch from '../assets/grocery/Masala/Coriander Powder(catch).png'
import coriander_powder_tata from '../assets/grocery/Masala/Coriander Powder(tata).png'
import deggi_mirch from '../assets/grocery/Masala/Deggi mirch(MDH).png'
import garam_masala_catch from '../assets/grocery/Masala/Garam Masala(catch).png'
import garam_masala_everest from '../assets/grocery/Masala/Garam masala(everest).png'
import garam_masala_mdh from '../assets/grocery/Masala/Garam masala(MDH).png'
import garam_masala_tata from '../assets/grocery/Masala/Garam masala(tata).png'
import ginger_garlic from '../assets/grocery/Masala/Ginger garlic.png'
import jeera_powder_catch from '../assets/grocery/Masala/Jeera powder(catch).png'
import kashmiri_mirch_mdh from '../assets/grocery/Masala/Kashmiri mirch(MDH).png'
import kashmiri_powder_everest from '../assets/grocery/Masala/Kashmiri mirch(everest).png'
import kitchen_king_everest from '../assets/grocery/Masala/Kitchen king(everest).png'
import kitchen_king_mdh from '../assets/grocery/Masala/Kitchen king(MDH).png'
import kitchen_king_tata from '../assets/grocery/Masala/Kitchen king(tata).png'
import meat_masala_catch from '../assets/grocery/Masala/Meat masala(catch).png'
import meat_masala_mdh from '../assets/grocery/Masala/Meat masala(MDH).png'
import meat_masala_tata from '../assets/grocery/Masala/Meat masala(tata).png'
import sabji_masala_everest from '../assets/grocery/Masala/Sabji masala(everest).png'
import sabji_masala_goldie from '../assets/grocery/Masala/Sabji masala(goldie).png'
import shahi_paneer_MDH from '../assets/grocery/Masala/Shahi paneer(MDH).png'
import turmeric_powder_catch from '../assets/grocery/Masala/Turmeric powder(catch).png'
import turmeric_powder_flipcart from '../assets/grocery/Masala/Turmeric powder(flipcart).png'
// Nuts & Seeds
import masoor_black_flipcart from '../assets/grocery/Nuts & Seeds/Black Masoor dal.png'
import chanaDal_fortune from '../assets/grocery/Nuts & Seeds/Chana Dal(fortune).png'
import chana_rajdhani from '../assets/grocery/Nuts & Seeds/Chana rajdhani.png'
import chana_flipcart from '../assets/grocery/Nuts & Seeds/Chana.png'
import chanaDal_flipcart from '../assets/grocery/Nuts & Seeds/Chana dal.png'
import kabuli_flipcart from '../assets/grocery/Nuts & Seeds/Kabuli Chana(flipcart).png'
import kabuli_fortune from '../assets/grocery/Nuts & Seeds/Kabuli Chana(fortune).png'
import masoor_flipcart from '../assets/grocery/Nuts & Seeds/Masoor dal.png'
import mixed_dal from '../assets/grocery/Nuts & Seeds/Mixed dal.png'
import moong_dal_Chhilka from '../assets/grocery/Nuts & Seeds/Moong dal(chhilka).png'
import moong_dal_tata from '../assets/grocery/Nuts & Seeds/Moong dal(tata).png'
import moong from '../assets/grocery/Nuts & Seeds/Moong.png'
import moong_dal_flipcart from '../assets/grocery/Nuts & Seeds/Moong dal.png'
import rajma_flipcart from '../assets/grocery/Nuts & Seeds/Rajma(flipcart).png'
import rajma_fortune from '../assets/grocery/Nuts & Seeds/Rajma.png'
import soyachunk_flipcart from '../assets/grocery/Nuts & Seeds/Soya Chunk(flipcart).png'
import soyachunk_fortune from '../assets/grocery/Nuts & Seeds/Soya Chunk(fortune).png'
import Toor_dal from '../assets/grocery/Nuts & Seeds/Toor dal.png'
import urad_dal from '../assets/grocery/Nuts & Seeds/Urad dal.png'
import pea_flipcart from '../assets/grocery/Nuts & Seeds/White Pea.png'
// Sugar & Salt
import salt_black from '../assets/grocery/Suger & Salt/Black Salt.png'
import salt_pink from '../assets/grocery/Suger & Salt/Pink Salt.png'
import rock_salt_nature from '../assets/grocery/Suger & Salt/Black Salt.png'
import rock_salt_organic from '../assets/grocery/Suger & Salt/Rock Salt(organic).png'
import rock_salt_tata from '../assets/grocery/Suger & Salt/Rock Salt(tata).png'
import salt_immuno from '../assets/grocery/Suger & Salt/Salt Immuno.png'
import salt_lite from '../assets/grocery/Suger & Salt/Salt lite.png'
import salt from '../assets/grocery/Suger & Salt/Salt.png'
import sugarfree from '../assets/grocery/Suger & Salt/Suger free.png'
import sugar_sulpharfree from '../assets/grocery/Suger & Salt/Suger Sulpharfree.png'
import suger from '../assets/grocery/Suger & Salt/Suger.png'
// Whole Masala
import ajwain_flipcart from '../assets/grocery/Whole masala/Ajwain flipcart.png'
import ajwain_zoff from '../assets/grocery/Whole masala/Ajwain Zoff.png'
import cardamom_black from '../assets/grocery/Whole masala/Black Cardamom.png'
import black_peppar from '../assets/grocery/Whole masala/Black Peppar.png'
import black_peppar_flipcart from '../assets/grocery/Whole masala/Black Peppar(flipcart).png'
import cinnamon from '../assets/grocery/Whole masala/Cinnamon.png'
import clove_zoff from '../assets/grocery/Whole masala/Clove(Zoff).png'
import clove_flipcart from '../assets/grocery/Whole masala/Clove(flipcart).png'
import coriander_flipcart from '../assets/grocery/Whole masala/Coriander(flipcart).png'
import fenugreek from '../assets/grocery/Whole masala/Fenugreek.png'
import funnel_flipcart from '../assets/grocery/Whole masala/Funnel Seeds(flipcart).png'
import funnel_zoff from '../assets/grocery/Whole masala/Funnel Seeds(Zoff).png'
import garam_masala from '../assets/grocery/Whole masala/Garam masala.png'
import javitri from '../assets/grocery/Whole masala/Javitri.png'
import jeera_catch from '../assets/grocery/Whole masala/Jeera(catch).png'
import jeera_zoff from '../assets/grocery/Whole masala/Jeera(Zoff).png'
import kasturi_methi from '../assets/grocery/Whole masala/Kasturi methi(Zoff).png'
import lal_mirch from '../assets/grocery/Whole masala/Lal mirch.png'
import mustard_rai from '../assets/grocery/Whole masala/Mustard rai.png'
import tejpatta from '../assets/grocery/Whole masala/Tejpatta.png'


let allData = [
  {
    id: 1,
    name: "Apple",
    img: apple,
    price: "₹160",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "15% off",
  },
  {
    id: 2,
    name: "Bitter Gourd",
    img: bitterGourd,
    price: "₹80",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Black Grapes",
    img: blackgrapes,
    price: "₹140",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Brocoli",
    img: brocoli,
    price: "₹80",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Banana",
    img: banana,
    price: "₹60",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Beans",
    img: beans,
    price: "₹50",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 7,
    name: "Berry",
    img: berry,
    price: "₹120",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 8,
    name: "Bottle Gourd",
    img: bottleGourd,
    price: "₹40",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",
  },
  {
    id: 9,
    name: "Custard Apple",
    img: custardApple,
    price: "₹180",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 10,
    name: "Cabbage",
    img: cabbage,
    price: "₹50",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 11,
    name: "Grapes",
    img: grapes,
    price: "₹140",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 12,
    name: "Guava",
    img: guava,
    price: "₹70",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 13,
    name: "Capsicum",
    img: capsicum,
    price: "₹50",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 13,
    name: "Carrot",
    img: carrot,
    price: "₹40",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 14,
    name: "Lichi",
    img: lichi,
    price: "₹80",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 15,
    name: "Mango",
    img: mango,
    price: "₹60",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 16,
    name: "Ladies Finger",
    img: ladiesFinger,
    price: "₹70",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 17,
    name: "Onion",
    img: onion,
    price: "₹40",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 18,
    name: "Pea",
    img: pea,
    price: "₹50",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 19,
    name: "Plum",
    img: plum,
    price: "₹150",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 20,
    name: "Potato",
    img: potato,
    price: "₹30",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 21,
    name: "Pumpkin",
    img: pumpkin,
    price: "₹50",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",
  },
  {
    id: 22,
    name: "Pomegranate",
    img: pomegranate,
    price: "₹130",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
  {
    id: 23,
    name: "Radish",
    img: radish,
    price: "₹30",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 24,
    name: "Watermelon",
    img: watermelon,
    price: "₹80",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 25,
    name: "Tomato",
    img: tomato,
    price: "₹40",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 26,
    name: "Chiku",
    img: chiku,
    price: "₹80",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 27,
    name: "Gooseberry",
    img: gooseberry,
    price: "₹40",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 28,
    name: "CauliFlower",
    img: cauliflower,
    price: "₹60",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 29,
    name: "Cucumber",
    img: cucumber,
    price: "₹50",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",
  },
  {
    id: 30,
    name: "Mosambi",
    img: mosambi,
    price: "₹60",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
  {
    id: 31,
    name: "Papaya",
    img: papaya,
    price: "₹70",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 32,
    name: "Ginger",
    img: ginger,
    price: "₹80",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 33,
    name: "Methi",
    img: methi,
    price: "₹40",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 34,
    name: "Pineapple",
    img: pineapple,
    price: "₹100",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 35,
    name: "Beet root",
    img: beetroot,
    price: "₹40",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
  {
    id: 36,
    name: "Mushroom",
    img: mushroom,
    price: "₹60",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 37,
    name: "Orange",
    img: orange,
    price: "₹70",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
  {
    id: 38,
    name: "Spinach",
    img: spinach,
    price: "₹80",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 39,
    name: "Aashirvaad Atta",
    img: atta_ashirvaad,
    price: "₹220",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 40,
    name: "Fortune Atta",
    img: atta_fortune,
    price: "₹210",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 41,
    name: "Fortune Besan",
    img: besan_fortune,
    price: "₹99",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 42,
    name: "Rajdhani Besan",
    img: besan_rajdhani,
    price: "109",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 43,
    name: "Daliya Rajdhani",
    img: daliya_rajdhani,
    price: "76",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 44,
    name: "Fortune Basmati Rice",
    img: rice_fortune,
    price: "₹535",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 45,
    name: "India Gate Basmati Rice (Everyday)",
    img: indiaGate_Everyday,
    price: "₹355",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 46,
    name: "India Gate Basmati Rice (Mini Mogra)",
    img: indiaGate_miniMogra,
    price: "₹290",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 47,
    name: "India Gate Basmati Rice (Mogra)",
    img: indiaGate_Mogra,
    price: "₹345",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 48,
    name: "India Gate Basmati Rice (Regular)",
    img: indiaGate_Regular,
    price: "₹380",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 49,
    name: "India Gate Basmati Rice (Super)",
    img: indiaGate_Super,
    price: "₹780",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 50,
    name: "Nature Fresh Atta",
    img: Nature_fresh,
    price: "₹230",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 51,
    name: "Fortune Poha",
    img: poha_fortune,
    price: "₹51",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 52,
    name: "Fortune Maida",
    img: maida_fortune,
    price: "₹40",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 53,
    name: "Rajdhani Maida",
    img: maida_rajdhani,
    price: "₹40",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 54,
    name: "Rajdhani Poha",
    img: poha_rajdhani,
    price: "₹40",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 55,
    name: "Almonds",
    img: almonds,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 56,
    name: "Dates",
    img: dates,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 57,
    name: "Peanut",
    img: peanut,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 58,
    name: "Makhana Classic",
    img: makhana_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 59,
    name: "Makhana ZOFF",
    img: makhana_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 60,
    name: "Chia Seeds",
    img: chia_seeds,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 61,
    name: "Raisins(Kismis)",
    img: raisins_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 61,
    name: "Raisins(Kismis)",
    img: raisins_tata,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 62,
    name: "Pumpkin Seeds",
    img: pumpkin_seeds,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 63,
    name: "Anjir Classic",
    img: anjir,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 64,
    name: "Cashew Classic Kaju",
    img: cashew_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 65,
    name: "Cashew ZOFF Kaju ",
    img: cashew_tata,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 66,
    name: "Walnut ",
    img: walnut,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 67,
    name: "Aashirvaad Ghee ",
    img: ghee_ashirvaad,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 68,
    name: "Amul Ghee ",
    img: ghee_amul,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 69,
    name: "Ananda Ghee ",
    img: ghee_ananda,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 70,
    name: "Dalda 1kg",
    img: dalda_1kg,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 71,
    name: "Dalda 5kg ",
    img: dalda_5kg,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 72,
    name: "Dhara Oil ",
    img: oil_dhara,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 73,
    name: "Dhara Oil Pouch ",
    img: oil_dhara_pouch,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 74,
    name: "Fortune Oil ",
    img: oil_fortune,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 75,
    name: "Fortune Oil 2.5 ltr ",
    img: oil_fortune_2,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 76,
    name: "Fortune Oil Pouch ",
    img:oil_fortune_pouch,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 77,
    name: "Godrej Ghee ",
    img: ghee_godrej,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 78,
    name: "Govardhan Ghee ",
    img: ghee_govardhan,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 79,
    name: "Fortune Refine ",
    img: refine_fortune,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 80,
    name: "Chat Masala",
    img:chat_masala ,
    price: "₹60",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 81,
    name: "Chhole Masala",
    img:Chhole_masala ,
    price: "₹50",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 82,
    name: "Chicken Masala",
    img:chicken_masala_catch,
    price: "₹80",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 83,
    name: "Chicken Masala",
    img:chicken_masala_mdh ,
    price: "₹79",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 84,
    name: "Chilli Powder",
    img:chilli_powder_catch ,
    price: "₹90",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 85,
    name: "Coriander Powder",
    img:coriander_powder_catch ,
    price: "35",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 86,
    name: "Coriander Powder",
    img:coriander_powder_tata ,
    price: "45",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 87,
    name: "Deggi Mirch",
    img:deggi_mirch ,
    price: "95",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 88,
    name: "Garam Masala",
    img:garam_masala_catch ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 89,
    name: "Garam Masala",
    img:garam_masala_everest ,
    price: "80",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 90,
    name: "Garam Masala",
    img:garam_masala_mdh ,
    price: "95",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 91,
    name: "Garam Masala",
    img:garam_masala_tata ,
    price: "110",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 92,
    name: "Ginger & Garlic Paste",
    img:ginger_garlic ,
    price: "45",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 93,
    name: "Jeera Powder",
    img:jeera_powder_catch ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 94,
    name: "Kashmiri Mirch",
    img:kashmiri_mirch_mdh ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 95,
    name: "Kashmiri Powder",
    img:kashmiri_powder_everest ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 96,
    name: "Kitchen King",
    img:kitchen_king_everest ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 97,
    name: "Kitchen King",
    img:kitchen_king_mdh ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  { 
    id: 98,
    name: "Kitchen King",
    img:kitchen_king_tata ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 99,
    name: "Meat Masala",
    img:meat_masala_catch ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 100,
    name: "Meat Masala",
    img:meat_masala_mdh ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 101,
    name: "Meat Masala",
    img:meat_masala_tata ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 102,
    name: "Sabji Masala",
    img:sabji_masala_everest ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 103,
    name: "Sabji Masala",
    img:sabji_masala_goldie ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 104,
    name: "Shahi Paneer Masala",
    img:shahi_paneer_MDH,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 105,
    name: "Turmeric Powder",
    img:turmeric_powder_catch ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 106,
    name: "Turmeric Powder",
    img:turmeric_powder_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 107,
    name: "Black Masoor Dal",
    img:masoor_black_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 108,
    name: "Fortune Chana Dal",
    img:chanaDal_fortune ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 109,
    name: "Rajdhani Chana",
    img:chana_rajdhani ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 110,
    name: "Classic Chana",
    img:chana_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 111,
    name: "Classic Chana Dal",
    img:chanaDal_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 112,
    name: "Classic Kabuli Chana",
    img:kabuli_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 113,
    name: "Fortune Kabuli Chana",
    img:kabuli_fortune ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 114,
    name: "Classic Masoor Dal",
    img:masoor_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 115,
    name: "Mixed Dal",
    img:mixed_dal ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 116,
    name: "Moong Dal",
    img:moong_dal_Chhilka ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 117,
    name: "Moong Dal",
    img:moong_dal_tata ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 118,
    name: "Moong Saboot",
    img:moong ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 119,
    name: "Classic Moong Dal",
    img:moong_dal_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 120,
    name: "Classic Rajma",
    img:rajma_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 121,
    name: "Fortune Rajma",
    img:rajma_fortune ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 122,
    name: "Soya Chunk",
    img:soyachunk_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 123,
    name: "Soya Chunk",
    img:soyachunk_fortune ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 124,
    name: "Classic Toor Dal",
    img:Toor_dal ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 125,
    name: "Urad Dal",
    img:urad_dal ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 126,
    name: "Classic White Pea",
    img:pea_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 127,
    name: "Pink Salt",
    img: salt_pink,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 128,
    name: "Black Salt",
    img: salt_black,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 129,
    name: "Tata Salt",
    img: salt,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 130,
    name: "Rock Salt",
    img: rock_salt_nature,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 131,
    name: "Rock Salt",
    img: rock_salt_tata,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 132,
    name: "Rock Salt",
    img: rock_salt_organic,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 133,
    name: "Salt Lite",
    img: salt_lite,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 134,
    name: "Sugar Free",
    img: sugarfree,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 135,
    name: "Sulpharfree Sugar",
    img: sugar_sulpharfree,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 136,
    name: "Fortune Sugar",
    img: suger,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 137,
    name: "Salt Immuno",
    img: salt_immuno,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 138,
    name: "Classic Ajwain",
    img: ajwain_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 139,
    name: "Zoff Ajwain",
    img: ajwain_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 140,
    name: "Black Cardamom",
    img: cardamom_black,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 141,
    name: "Black Peppar",
    img: black_peppar,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 142,
    name: "Classic Black Peppar",
    img: black_peppar_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 143,
    name: "Cinnamon",
    img: cinnamon,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 144,
    name: "Clove/Laung ZOff",
    img: clove_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 145,
    name: "Classic Clove/Laung",
    img: clove_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 146,
    name: "Classic Coriander",
    img: coriander_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 147,
    name: "Fenugreek/Methi Zoff",
    img: fenugreek,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 148,
    name: "Classic Funnel Seeds",
    img: funnel_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 149,
    name: "Funnel Seeds Zoff",
    img: funnel_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 150,
    name: "Garam Masala",
    img: garam_masala,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 151,
    name: "Javitri",
    img: javitri,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 152,
    name: "Whole Jeera",
    img: jeera_catch,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 153,
    name: "Whole Jeera",
    img: jeera_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 154,
    name: "Kasturi Methi",
    img: kasturi_methi,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 155,
    name: "Lal Mirch",
    img: lal_mirch,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 156,
    name: "Classic Mustard Rai",
    img: mustard_rai,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 157,
    name: "Classic Tejpatta",
    img: tejpatta,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },

];
export default allData;
let allFruit=[
  {
    id: 1,
    name: "Apple",
    img: apple,
    price: "₹160",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "15% off",
  },
  {
    id: 2,
    name: "Black Grapes",
    img: blackgrapes,
    price: "₹140",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Banana",
    img: banana,
    price: "₹60",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Berry",
    img: berry,
    price: "₹120",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Custard Apple",
    img: custardApple,
    price: "₹180",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Grapes",
    img: grapes,
    price: "₹140",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 7,
    name: "Guava",
    img: guava,
    price: "₹70",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 8,
    name: "Lichi",
    img: lichi,
    price: "₹80",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 9,
    name: "Mango",
    img: mango,
    price: "₹60",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 10,
    name: "Plum",
    img: plum,
    price: "₹150",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 11,
    name: "Pomegranate",
    img: pomegranate,
    price: "₹130",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
  {
    id: 12,
    name: "Watermelon",
    img: watermelon,
    price: "₹80",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 13,
    name: "Chiku",
    img: chiku,
    price: "₹80",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 14,
    name: "Gooseberry",
    img: gooseberry,
    price: "₹40",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 15,
    name: "Mosambi",
    img: mosambi,
    price: "₹60",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
  {
    id: 16,
    name: "Papaya",
    img: papaya,
    price: "₹70",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 17,
    name: "Pineapple",
    img: pineapple,
    price: "₹100",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 18,
    name: "Beet root",
    img: beetroot,
    price: "₹40",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
  {
    id: 19,
    name: "Orange",
    img: orange,
    price: "₹70",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
]
export {allFruit}

let fruit = [
  {
    id: 1,
    name: "Apple",
    img: apple,
    price: "₹100",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Banana",
    img: banana,
    price: "₹60",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Kiwi",
    img: kiwi,
    price: "₹100",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Mango",
    img: berry,
    price: "₹80",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Custard Apple",
    img: blackgrapes,
    price: "₹100",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Guava",
    img: guava,
    price: "₹80",
    offer: "10% off",
  },
];
export { fruit };

let allVegi=[
  {
    id: 1,
    name: "Bitter Gourd",
    img: bitterGourd,
    price: "₹80",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Brocoli",
    img: brocoli,
    price: "₹80",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Beans",
    img: beans,
    price: "₹50",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Bottle Gourd",
    img: bottleGourd,
    price: "₹40",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Cabbage",
    img: cabbage,
    price: "₹50",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Capsicum",
    img: capsicum,
    price: "₹50",
    category: "Fruits",
    variety: "Tropical Fruits",
    offer: "10% off",
  },
  {
    id: 7,
    name: "Carrot",
    img: carrot,
    price: "₹40",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 8,
    name: "Ladies Finger",
    img: ladiesFinger,
    price: "₹70",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 9,
    name: "Onion",
    img: onion,
    price: "₹40",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 10,
    name: "Pea",
    img: pea,
    price: "₹50",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 11,
    name: "Potato",
    img: potato,
    price: "₹30",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 12,
    name: "Pumpkin",
    img: pumpkin,
    price: "₹50",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",
  },
  {
    id: 13,
    name: "Radish",
    img: radish,
    price: "₹30",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 14,
    name: "CauliFlower",
    img: cauliflower,
    price: "₹60",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 15,
    name: "Cucumber",
    img: cucumber,
    price: "₹50",
    category: "Vegetables",
    variety: "Marrow Vegi",
    offer: "10% off",
  },
  {
    id: 16,
    name: "Mosambi",
    img: mosambi,
    price: "₹60",
    category: "Fruits",
    variety: "Citrus Fruits",
    offer: "10% off",
  },
  {
    id: 17,
    name: "Ginger",
    img: ginger,
    price: "₹80",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 18,
    name: "Methi",
    img: methi,
    price: "₹40",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
  {
    id: 19,
    name: "Mushroom",
    img: mushroom,
    price: "₹60",
    category: "Vegetables",
    variety: "Root Vegi",
    offer: "10% off",
  },
  {
    id: 20,
    name: "Spinach",
    img: spinach,
    price: "₹80",
    category: "Vegetables",
    variety: "Leafy Green",
    offer: "10% off",
  },
]
export {allVegi}

let vegi = [
  {
    id: 1,
    name: "Brocoli",
    img: brocoli,
    price: "₹80",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Onion",
    img: onion,
    price: "₹50",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Pumpkin",
    img: pumpkin,
    price: "₹60",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Spinach",
    img: spinach,
    price: "₹40",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Capsicum",
    img: capsicum,
    price: "₹60",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Cucumber",
    img: cucumber,
    price: "₹40",
    offer: "10% off",
  },
];
export { vegi };

let allMasala=[
  {
    id: 1,
    name: "Chat Masala",
    img:chat_masala ,
    price: "₹60",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Chhole Masala",
    img:Chhole_masala ,
    price: "₹50",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Chicken Masala",
    img:chicken_masala_catch,
    price: "₹80",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Chicken Masala",
    img:chicken_masala_mdh ,
    price: "₹79",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Chilli Powder",
    img:chilli_powder_catch ,
    price: "₹90",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Coriander Powder",
    img:coriander_powder_catch ,
    price: "35",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 7,
    name: "Coriander Powder",
    img:coriander_powder_tata ,
    price: "45",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 8,
    name: "Deggi Mirch",
    img:deggi_mirch ,
    price: "95",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 9,
    name: "Garam Masala",
    img:garam_masala_catch ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 10,
    name: "Garam Masala",
    img:garam_masala_everest ,
    price: "80",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 11,
    name: "Garam Masala",
    img:garam_masala_mdh ,
    price: "95",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 12,
    name: "Garam Masala",
    img:garam_masala_tata ,
    price: "110",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 13,
    name: "Ginger & Garlic Paste",
    img:ginger_garlic ,
    price: "45",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 14,
    name: "Jeera Powder",
    img:jeera_powder_catch ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 15,
    name: "Kashmiri Mirch",
    img:kashmiri_mirch_mdh ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 16,
    name: "Kashmiri Powder",
    img:kashmiri_powder_everest ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 17,
    name: "Kitchen King",
    img:kitchen_king_everest ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 18,
    name: "Kitchen King",
    img:kitchen_king_mdh ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  { 
    id: 19,
    name: "Kitchen King",
    img:kitchen_king_tata ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 20,
    name: "Meat Masala",
    img:meat_masala_catch ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 21,
    name: "Meat Masala",
    img:meat_masala_mdh ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 22,
    name: "Meat Masala",
    img:meat_masala_tata ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 23,
    name: "Sabji Masala",
    img:sabji_masala_everest ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 24,
    name: "Sabji Masala",
    img:sabji_masala_goldie ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 25,
    name: "Shahi Paneer Masala",
    img:shahi_paneer_MDH,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 26,
    name: "Turmeric Powder",
    img:turmeric_powder_catch ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
  {
    id: 27,
    name: "Turmeric Powder",
    img:turmeric_powder_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Masala",
    offer: "15% off",
  },
]
export {allMasala}

let masala = [
  {
    id: 1,
    name: "Chicken Masala",
    img: chicken_masala_catch,
    price: "₹80",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Chilli Powder",
    img: chilli_powder_catch,
    price: "₹90",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Coriander Powder",
    img: coriander_powder_catch,
    price: "₹35",
    offer: "15% off",
  },
  {
    id: 4,
    name: "Garam Masala",
    img: garam_masala_catch,
    price: "₹90",
    offer: "15% off",
  },
  {
    id: 5,
    name: "Kitchen King",
    img: kitchen_king_mdh,
    price: "₹90",
    offer: "15% off",
  },
  {
    id: 6,
    name: "Meat Masala",
    img: meat_masala_catch,
    price: "₹90",
    offer: "15% off",
  },
];
export {masala}

let allGrains=[
  {
    id: 1,
    name: "Aashirvaad Atta",
    img: atta_ashirvaad,
    price: "₹220",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Fortune Atta",
    img: atta_fortune,
    price: "₹210",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Fortune Besan",
    img: besan_fortune,
    price: "₹99",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Rajdhani Besan",
    img: besan_rajdhani,
    price: "109",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Daliya Rajdhani",
    img: daliya_rajdhani,
    price: "76",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Fortune Basmati Rice",
    img: rice_fortune,
    price: "₹535",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 7,
    name: "India Gate Basmati Rice (Everyday)",
    img: indiaGate_Everyday,
    price: "₹355",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 8,
    name: "India Gate Basmati Rice (Mini Mogra)",
    img: indiaGate_miniMogra,
    price: "₹290",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 9,
    name: "India Gate Basmati Rice (Mogra)",
    img: indiaGate_Mogra,
    price: "₹345",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 10,
    name: "India Gate Basmati Rice (Regular)",
    img: indiaGate_Regular,
    price: "₹380",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 11,
    name: "India Gate Basmati Rice (Super)",
    img: indiaGate_Super,
    price: "₹780",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 12,
    name: "Nature Fresh Atta",
    img: Nature_fresh,
    price: "₹230",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 13,
    name: "Fortune Poha",
    img: poha_fortune,
    price: "₹51",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 14,
    name: "Fortune Maida",
    img: maida_fortune,
    price: "₹40",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 15,
    name: "Rajdhani Maida",
    img: maida_rajdhani,
    price: "₹40",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 16,
    name: "Rajdhani Poha",
    img: poha_rajdhani,
    price: "₹40",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
]
export {allGrains}

let grains=[
    {
        id: 1,
        name: "Fortune Atta",
        img: atta_fortune,
        price: "₹210",
        offer: "10% off",
      },
      {
        id: 2,
        name: "Fortune Basmati Rice",
        img: rice_fortune,
        price: "₹535",
        offer: "10% off",
      },
      {
        id: 3,
        name: "Poha",
        img: poha_fortune,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 4,
        name: "Besan",
        img: besan_fortune,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 5,
        name: "Daliya",
        img: daliya_rajdhani,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 6,
        name: "Maida",
        img: maida_fortune,
        price: "₹51",
        offer: "10% off",
      },

]
export {grains}

let allNuts_seed=[
  {
    id: 1,
    name: "Black Masoor Dal",
    img:masoor_black_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 2,
    name: "Fortune Chana Dal",
    img:chanaDal_fortune ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 3,
    name: "Rajdhani Chana",
    img:chana_rajdhani ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 4,
    name: "Classic Chana",
    img:chana_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 5,
    name: "Classic Chana Dal",
    img:chanaDal_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 6,
    name: "Classic Kabuli Chana",
    img:kabuli_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 7,
    name: "Fortune Kabuli Chana",
    img:kabuli_fortune ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 8,
    name: "Classic Masoor Dal",
    img:masoor_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 9,
    name: "Mixed Dal",
    img:mixed_dal ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 10,
    name: "Moong Dal",
    img:moong_dal_Chhilka ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 11,
    name: "Moong Dal",
    img:moong_dal_tata ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 12,
    name: "Moong Saboot",
    img:moong ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 13,
    name: "Classic Moong Dal",
    img:moong_dal_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 14,
    name: "Classic Rajma",
    img:rajma_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 15,
    name: "Fortune Rajma",
    img:rajma_fortune ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 16,
    name: "Soya Chunk",
    img:soyachunk_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 17,
    name: "Soya Chunk",
    img:soyachunk_fortune ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 18,
    name: "Classic Toor Dal",
    img:Toor_dal ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 19,
    name: "Urad Dal",
    img:urad_dal ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
  {
    id: 20,
    name: "Classic White Pea",
    img:pea_flipcart ,
    price: "90",
    category: "Grocery",
    variety: "Nuts Seed",
    offer: "15% off",
  },
]
export {allNuts_seed}

let nuts_Seeds=[
    {
        id: 1,
        name: "Rajdhani Chana",
        img: chana_rajdhani,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 2,
        name: "Soya Chunks",
        img: soyachunk_fortune,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 3,
        name: "Rajma",
        img: rajma_fortune,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 4,
        name: "Mixed Dal",
        img: mixed_dal,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 5,
        name: "Kabuli Chana",
        img: kabuli_fortune,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 6,
        name: "Chana Dal",
        img: chanaDal_fortune,
        price: "₹51",
        offer: "10% off",
      },
]
export {nuts_Seeds}

let allDry_Fruits=[
  {
    id: 1,
    name: "Almonds",
    img: almonds,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Dates",
    img: dates,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Peanut",
    img: peanut,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Makhana Classic",
    img: makhana_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Makhana ZOFF",
    img: makhana_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Chia Seeds",
    img: chia_seeds,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 7,
    name: "Raisins(Kismis)",
    img: raisins_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 8,
    name: "Raisins(Kismis)",
    img: raisins_tata,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 9,
    name: "Pumpkin Seeds",
    img: pumpkin_seeds,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 10,
    name: "Anjir Classic",
    img: anjir,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 11,
    name: "Cashew Classic Kaju",
    img: cashew_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 12,
    name: "Cashew ZOFF Kaju ",
    img: cashew_tata,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
  {
    id: 13,
    name: "Walnut ",
    img: walnut,
    price: "₹51",
    category: "Grocery",
    variety: "Dry Fruits",
    offer: "10% off",
  },
]
export {allDry_Fruits}

let dry_fruits=[
    {
        id: 1,
        name: "Almonds",
        img: almonds,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 2,
        name: "Dates",
        img: dates,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 3,
        name: "Peanut",
        img: peanut,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 4,
        name: "Makhana",
        img: makhana_zoff,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 5,
        name: "Chia Seeds",
        img: chia_seeds,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 6,
        name: "Raisins(Kismis)",
        img: raisins_tata,
        price: "₹51",
        offer: "10% off",
      },
]
export {dry_fruits}

let allGhee_oil=[
  {
    id: 1,
    name: "Aashirvaad Ghee ",
    img: ghee_ashirvaad,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Amul Ghee ",
    img: ghee_amul,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Ananda Ghee ",
    img: ghee_ananda,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Dalda 1kg",
    img: dalda_1kg,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Dalda 5kg ",
    img: dalda_5kg,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Dhara Oil ",
    img: oil_dhara,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 7,
    name: "Dhara Oil Pouch ",
    img: oil_dhara_pouch,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 8,
    name: "Fortune Oil ",
    img: oil_fortune,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 9,
    name: "Fortune Oil 2.5 ltr ",
    img: oil_fortune_2,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 10,
    name: "Fortune Oil Pouch ",
    img:oil_fortune_pouch,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 11,
    name: "Godrej Ghee ",
    img: ghee_godrej,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 12,
    name: "Govardhan Ghee ",
    img: ghee_govardhan,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
  {
    id: 13,
    name: "Fortune Refine ",
    img: refine_fortune,
    price: "₹51",
    category: "Grocery",
    variety: "Ghee Oil",
    offer: "10% off",
  },
]
export {allGhee_oil}

let ghee_oil=[
    {
        id: 1,
        name: "Aashirvaad Ghee",
        img: ghee_ashirvaad,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 2,
        name: "Dhara Oil",
        img: oil_dhara,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 3,
        name: "Dalda",
        img: dalda_1kg,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 4,
        name: "Refine",
        img: refine_fortune,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 5,
        name: "Govardhan Ghee",
        img: ghee_govardhan,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 6,
        name: "Fortune Oil",
        img: oil_fortune,
        price: "₹51",
        offer: "10% off",
      },
]
export {ghee_oil}

let allSugar_salt=[
  {
    id: 1,
    name: "Pink Salt",
    img: salt_pink,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Black Salt",
    img: salt_black,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Tata Salt",
    img: salt,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Rock Salt",
    img: rock_salt_nature,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Rock Salt",
    img: rock_salt_tata,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Rock Salt",
    img: rock_salt_organic,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 7,
    name: "Salt Lite",
    img: salt_lite,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 8,
    name: "Sugar Free",
    img: sugarfree,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 9,
    name: "Sulpharfree Sugar",
    img: sugar_sulpharfree,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 10,
    name: "Fortune Sugar",
    img: suger,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
  {
    id: 11,
    name: "Salt Immuno",
    img: salt_immuno,
    price: "₹51",
    category: "Grocery",
    variety: "Sugar Salt",
    offer: "10% off",
  },
]
export {allSugar_salt}

let suger_salt=[
    {
        id: 1,
        name: "Pink Salt",
        img: salt_pink,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 2,
        name: "Balck Salt",
        img: salt_black,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 3,
        name: "Tata Salt",
        img: salt,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 4,
        name: "Rock Salt",
        img: rock_salt_organic,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 4,
        name: "Salt Lite",
        img: salt_lite,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 5,
        name: "Sugar Free",
        img: sugarfree,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 6,
        name: "Sulpharfree Sugar",
        img: sugar_sulpharfree,
        price: "₹51",
        offer: "10% off",
      },
]
export {suger_salt}

let allWhole_masala=[
  {
    id: 1,
    name: "Classic Ajwain",
    img: ajwain_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 2,
    name: "Zoff Ajwain",
    img: ajwain_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 3,
    name: "Black Cardamom",
    img: cardamom_black,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 4,
    name: "Black Peppar",
    img: black_peppar,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 5,
    name: "Classic Black Peppar",
    img: black_peppar_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 6,
    name: "Cinnamon",
    img: cinnamon,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 7,
    name: "Clove/Laung ZOff",
    img: clove_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 8,
    name: "Classic Clove/Laung",
    img: clove_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 9,
    name: "Classic Coriander",
    img: coriander_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 10,
    name: "Fenugreek/Methi Zoff",
    img: fenugreek,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 11,
    name: "Classic Funnel Seeds",
    img: funnel_flipcart,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 12,
    name: "Funnel Seeds Zoff",
    img: funnel_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 13,
    name: "Garam Masala",
    img: garam_masala,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 14,
    name: "Javitri",
    img: javitri,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 15,
    name: "Whole Jeera",
    img: jeera_catch,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 16,
    name: "Whole Jeera",
    img: jeera_zoff,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 17,
    name: "Kasturi Methi",
    img: kasturi_methi,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 18,
    name: "Lal Mirch",
    img: lal_mirch,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 19,
    name: "Classic Mustard Rai",
    img: mustard_rai,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
  {
    id: 20,
    name: "Classic Tejpatta",
    img: tejpatta,
    price: "₹51",
    category: "Grocery",
    variety: "Whole masala",
    offer: "10% off",
  },
]
export {allWhole_masala}

let whole_masala=[
    {
        id: 1,
        name: "Ajwain",
        img: ajwain_zoff,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 2,
        name: "Cinnamon",
        img: cinnamon,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 3,
        name: "Garam Masala",
        img: garam_masala,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 4,
        name: "Funnel Seeds",
        img: funnel_zoff,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 5,
        name: "Jeera",
        img: jeera_catch,
        price: "₹51",
        offer: "10% off",
      },
      {
        id: 6,
        name: "Tejpatta",
        img: tejpatta,
        price: "₹51",
        offer: "10% off",
      },
]
export {whole_masala}