import apple from '../assets/fruits/apple.png'
import bitterGourd from '../assets/vegitables/bitter gourd.png'
import blackgrapes from '../assets/fruits/black grapes.png'
import brocoli from '../assets/vegitables/brocoli.png'
import banana from '../assets/fruits/banana.png'
import beans from '../assets/vegitables/beans.png'
import berry from '../assets/fruits/berry.png'
import bottleGourd from '../assets/vegitables/bottle gourd.png'
import custardApple from '../assets/fruits/custard apple.png'
import cabbage from '../assets/vegitables/cabbage.png'
import grapes from '../assets/fruits/grapes.png'
import guava from '../assets/fruits/guava.png'
import capsicum from '../assets/vegitables/capsicum.png'
import carrot from '../assets/vegitables/carrot.png'
import lichi from '../assets/fruits/lichi.png'
import mango from '../assets/fruits/mango.png'
import ladiesFinger from '../assets/vegitables/ladiesfinger.png'
import onion from '../assets/vegitables/onion.png'
import pea from '../assets/vegitables/pea.png'
import plum from '../assets/fruits/plum.png'
import potato from '../assets/vegitables/potato.png'
import pumpkin from '../assets/vegitables/pumpkin.png'
import pomegranate from '../assets/fruits/pomegranate.png'
import radish from '../assets/vegitables/radish.png'
import watermelon from '../assets/fruits/watermelon.png'
import tomato from '../assets/vegitables/tomato.png'
import chiku from '../assets/fruits/chiku.png'
import gooseberry from '../assets/fruits/gooseberry.png'
import cauliflower from '../assets/vegitables/cauliflower.png'
import cucumber from '../assets/vegitables/cucumber.png'
import mosambi from '../assets/fruits/mosambi.png'
import papaya from '../assets/fruits/papaya.png'
import ginger from '../assets/vegitables/ginger.png'
import methi from '../assets/vegitables/methi.png'
import pineapple from '../assets/fruits/pineapple.png'
import beetroot from '../assets/fruits/beetroot.png'
import mushroom from '../assets/vegitables/mushroom.png'
import orange from '../assets/fruits/orange.png'
import spinach from '../assets/vegitables/spinach.png'
import aashirvaad_atta from '../assets/grocery/Grains/Ashirvaad_atta.png'
import fortune_atta from '../assets/grocery/Grains/fortune_atta_5kg.png'
import fortune_rice from '../assets/grocery/Grains/Fortune_Basmati_Rice_5kg.png'
import indiaGate_Everyday from '../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Everyday.png'
import indiaGate_miniMogra from '../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Mini_Mogra.png'
import indiaGate_Mogra from '../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Mogra.png'
import indiaGate_Regular from '../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Regular.png'
import indiaGate_Super from '../assets/grocery/Grains/India_gate_Basmati_Rice_5kg_Super.png'
import Nature_fresh from '../assets/grocery/Grains/Nature_fresh_atta.png'
import poha from '../assets/grocery/Grains/Poha.png' 
import chicken_masala from '../assets/grocery/Masala/chicken_masala__catch.png'
import oil from '../assets/grocery/Oil/fortune_oil_1ltr.png'

let allData=[
    {
        id:1,
        name:"Apple",
        img:apple,
        price:"₹160",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"15% off",
    },
    {
        id:2,
        name:"Bitter Gourd",
        img:bitterGourd,
        price:"₹80",
        category:"Vegetables", 
        variety: "Marrow Vegi",
        offer:"10% off",
    },
    {
        id:3,
        name:"Black Grapes",
        img:blackgrapes,
        price:"₹140",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:4,
        name:"Brocoli",
        img:brocoli,
        price:"₹80",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:5,
        name:"Banana",
        img:banana,
        price:"₹60",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:6,
        name:"Beans",
        img:beans,
        price:"₹50",
         category:"Vegetables", 
        variety: "Leafy Green",
        offer:"10% off",
    },
    {
        id:7,
        name:"Berry",
        img:berry,
        price:"₹120",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:8,
        name:"Bottle Gourd",
        img:bottleGourd,
        price:"₹40",
        category:"Vegetables", 
        variety: "Marrow Vegi",
        offer:"10% off",
    },
    {
        id:9,
        name:"Custard Apple",
        img:custardApple,
        price:"₹180",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:10,
        name:"Cabbage",
        img:cabbage,
        price:"₹50",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:11,
        name:"Grapes",
        img:grapes,
        price:"₹140",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:12,
        name:"Guava",
        img:guava,
        price:"₹70",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:13,
        name:"Capsicum",
        img:capsicum,
        price:"₹50",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:13,
        name:"Carrot",
        img:carrot,
        price:"₹40",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:14,
        name:"Lichi",
        img:lichi,
        price:"₹80",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:15,
        name:"Mango",
        img:mango,
        price:"₹60",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:16,
        name:"Ladies Finger",
        img:ladiesFinger,
        price:"₹70",
         category:"Vegetables", 
        variety: "Leafy Green",
        offer:"10% off",
    },
    {
        id:17,
        name:"Onion",
        img:onion,
        price:"₹40",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:18,
        name:"Pea",
        img:pea,
        price:"₹50",
         category:"Vegetables", 
        variety: "Leafy Green",
        offer:"10% off",
    },
    {
        id:19,
        name:"Plum",
        img:plum,
        price:"₹150",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:20,
        name:"Potato",
        img:potato,
        price:"₹30",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:21,
        name:"Pumpkin",
        img:pumpkin,
        price:"₹50",
        category:"Vegetables", 
        variety: "Marrow Vegi",
        offer:"10% off",
    },
    {
        id:22,
        name:"Pomegranate",
        img:pomegranate,
        price:"₹130",
         category:"Fruits", 
        variety: "Citrus Fruits",
        offer:"10% off",
    },
    {
        id:23,
        name:"Radish",
        img:radish,
        price:"₹30",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:24,
        name:"Watermelon",
        img:watermelon,
        price:"₹80",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:25,
        name:"Tomato",
        img:tomato,
        price:"₹40",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:26,
        name:"Chiku",
        img:chiku,
        price:"₹80",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:27,
        name:"Gooseberry",
        img:gooseberry,
         price:"₹40",
         category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:28,
        name:"CauliFlower",
        img:cauliflower,
        price:"₹60",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:29,
        name:"Cucumber",
        img:cucumber,
        price:"₹50",
        category:"Vegetables", 
        variety: "Marrow Vegi",
        offer:"10% off",
    },
    {
        id:30,
        name:"Mosambi",
        img:mosambi,
        price:"₹60",
         category:"Fruits", 
        variety: "Citrus Fruits",
        offer:"10% off",
    },
    {
        id:31,
        name:"Papaya",
        img:papaya,
        price:"₹70",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:32,
        name:"Ginger",
        img:ginger,
        price:"₹80",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:33,
        name:"Methi",
        img:methi,
        price:"₹40",
        category:"Vegetables", 
        variety: "Leafy Green",
        offer:"10% off",
    },
    {
        id:34,
        name:"Pineapple",
        img:pineapple,
        price:"₹100",
        category:"Fruits", 
        variety: "Tropical Fruits",
        offer:"10% off",
    },
    {
        id:35,
        name:"Beet root",
        img:beetroot,
        price:"₹40",
        category:"Fruits", 
        variety: "Citrus Fruits",
        offer:"10% off",
    },
    {
        id:36,
        name:"Mushroom",
        img:mushroom,
        price:"₹60",
        category:"Vegetables", 
        variety: "Root Vegi",
        offer:"10% off",
    },
    {
        id:37,
        name:"Orange",
        img:orange,
        price:"₹70",
         category:"Fruits", 
        variety: "Citrus Fruits",
        offer:"10% off",
    },
    {
        id:38,
        name:"Spinach",
        img:spinach,
        price:"₹80",
        category:"Vegetables", 
        variety: "Leafy Green",
        offer:"10% off",
    },
    {
    id: 39,
    name: "Aashirvaad Atta",
    img: aashirvaad_atta, 
    price: "₹220",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 40,
    name: "Fortune Atta",
    img: fortune_atta, 
    price: "₹210",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 41,
    name: "Fortune Basmati Rice",
    img: fortune_rice, 
    price: "₹535",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 42,
    name: "India Gate Basmati Rice (Everyday)",
    img: indiaGate_Everyday, 
    price: "₹355",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 43,
    name: "India Gate Basmati Rice (Mini Mogra)",
    img: indiaGate_miniMogra, 
    price: "₹290",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 44,
    name: "India Gate Basmati Rice (Mogra)",
    img: indiaGate_Mogra, 
    price: "₹345",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 45,
    name: "India Gate Basmati Rice (Regular)",
    img: indiaGate_Regular, 
    price: "₹380",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 46,
    name: "India Gate Basmati Rice (Super)",
    img: indiaGate_Super, 
    price: "₹780",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 47,
    name: "Nature Fresh Atta",
    img: Nature_fresh, 
    price: "₹230",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 48,
    name: "Poha",
    img:poha , 
    price: "₹51",
    category: "Grocery",
    variety: "Grains",
    offer: "10% off",
  },
  {
    id: 49,
    name: "Chicken Masala",
    img:chicken_masala , 
    price: "₹80",
    category: "Grocery",
    variety: "Masala",
    offer: "10% off",
  },
  {
    id: 50,
    name: "oil",
    img:oil , 
    price: "₹51",
    category: "Grocery",
    variety: "oil",
    offer: "10% off",
  },
  

]

export default allData;

let masala=[
    {
        id: 1,
        name: "Chat Masala",
        img:chat_masala , 
        price: "₹60",
        category: "Grocery",
        variety: "Masala",
        offer: "10% off",
      },
      {
        id: 2,
        name: "Chhole Masala",
        img:Chhole_masala , 
        price: "₹50",
        category: "Grocery",
        variety: "Masala",
        offer: "10% off",
      },
      {
        id: 3,
        name: "Chicken Masala",
        img:chicken_masala_catch , 
        price: "₹80",
        category: "Grocery",
        variety: "Masala",
        offer: "10% off",
      },
      {
        id: 4,
        name: "Chicken Masala",
        img:chicken_masala_mdh , 
        price: "₹79",
        category: "Grocery",
        variety: "Masala",
        offer: "10% off",
      },
      {
        id: 5,
        name: "Chilli Powder",
        img:chilli_powder_catch , 
        price: "₹90",
        category: "Grocery",
        variety: "Masala",
        offer: "10% off",
      },
      {
        id: 6,
        name: "Coriander Powder",
        img:coriander_powder_catch , 
        price: "35",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      {
        id: 7,
        name: "Coriander Powder",
        img:coriander_powder_tata , 
        price: "45",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      {
        id: 8,
        name: "Deggi Mirch",
        img:deggi_mirch , 
        price: "95",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      {
        id: 9,
        name: "Garam Masala",
        img:garam_masala_catch , 
        price: "90",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      {
        id: 10,
        name: "Garam Masala",
        img:garam_masala_everest , 
        price: "80",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      {
        id: 11,
        name: "Garam Masala",
        img:garam_masala_mdh , 
        price: "95",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      {
        id: 12,
        name: "Garam Masala",
        img:garam_masala_tata , 
        price: "110",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      {
        id: 13,
        name: "Ginger & Garlic Paste",
        img:ginger_garlic , 
        price: "45",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      {
        id: 14,
        name: "Jeera Powder",
        img:jeera_powder_catch , 
        price: "90",
        category: "Grocery",
        variety: "Masala",
        offer: "15% off",
      },
      

]